<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $banks = [
      ['id' => '1', 'name' => 'BANK RAKYAT INDONESIA (PERSERO)', 'ksei_code' => '2'],
      ['id' => '2', 'name' => 'BANK MANDIRI (PERSERO)', 'ksei_code' => '8'],
      ['id' => '3', 'name' => 'BANK NEGARA INDONESIA (PERSERO)', 'ksei_code' => '9'],
      ['id' => '4', 'name' => 'BANK DANAMON INDONESIA', 'ksei_code' => '11'],
      ['id' => '5', 'name' => 'BANK PERMATA', 'ksei_code' => '13'],
      ['id' => '6', 'name' => 'BANK CENTRAL ASIA', 'ksei_code' => '14'],
      ['id' => '7', 'name' => 'BANK MAYBANK INDONESIA', 'ksei_code' => '16'],
      ['id' => '8', 'name' => 'PAN INDONESIABANK', 'ksei_code' => '19'],
      ['id' => '9', 'name' => 'BANK CIMB NIAGA', 'ksei_code' => '22'],
      ['id' => '10', 'name' => 'BANK UOB INDONESIA', 'ksei_code' => '23'],
      ['id' => '11', 'name' => 'BANK OCBC NISP', 'ksei_code' => '28'],
      ['id' => '12', 'name' => 'CITIBANK N.A.', 'ksei_code' => '31'],
      ['id' => '13', 'name' => 'JP MORGAN CHASEBANK, N.A.', 'ksei_code' => '32'],
      ['id' => '14', 'name' => 'BANK OF AMERICA, N.A.', 'ksei_code' => '33'],
      ['id' => '15', 'name' => 'BANK CHINA CONSTRUCTIONBANK INDONESIA', 'ksei_code' => '36'],
      ['id' => '16', 'name' => 'BANK ARTHA GRAHA INTERNASIONAL', 'ksei_code' => '37'],
      ['id' => '17', 'name' => 'BANGKOKBANK PUBLIC CO.LTD.', 'ksei_code' => '40'],
      ['id' => '18', 'name' => 'THEBANK OF TOKYO MITSUBISHI UFJ, LTD', 'ksei_code' => '42'],
      ['id' => '19', 'name' => 'BANK SUMITOMO MITSUI INDONESIA', 'ksei_code' => '45'],
      ['id' => '20', 'name' => 'BANK DBS INDONESIA', 'ksei_code' => '46'],
      ['id' => '21', 'name' => 'BANK RESONA PERDANIA', 'ksei_code' => '47'],
      ['id' => '22', 'name' => 'BANK MIZUHO INDONESIA', 'ksei_code' => '48'],
      ['id' => '23', 'name' => 'STANDARD CHARTEREDBANK', 'ksei_code' => '50'],
      ['id' => '24', 'name' => 'THE ROYALBANK OF SCOTLAND, N.V', 'ksei_code' => '52'],
      ['id' => '25', 'name' => 'BANK CAPITAL INDONESIA', 'ksei_code' => '54'],
      ['id' => '26', 'name' => 'BANK BNP PARIBAS INDONESIA', 'ksei_code' => '57'],
      ['id' => '27', 'name' => 'RABOBANK INTERNASIONAL INDONESIA', 'ksei_code' => '60'],
      ['id' => '28', 'name' => 'ANZ INDONESIA', 'ksei_code' => '61'],
      ['id' => '29', 'name' => 'DEUTSCHEBANK AG', 'ksei_code' => '67'],
      ['id' => '30', 'name' => 'BANK OF CHINA (HONGKONG) LIMITED', 'ksei_code' => '69'],
      ['id' => '31', 'name' => 'BANK BUMI ARTA', 'ksei_code' => '76'],
      ['id' => '32', 'name' => 'BANK HSBC INDONESIA', 'ksei_code' => '87'],
      ['id' => '33', 'name' => 'BANK JTRUST INDONESIA', 'ksei_code' => '95'],
      ['id' => '34', 'name' => 'BANK MAYAPADA INTERNASIONAL', 'ksei_code' => '97'],
      ['id' => '35', 'name' => 'BPD JAWA BARAT DAN BANTEN', 'ksei_code' => '110'],
      ['id' => '36', 'name' => 'BANK DKI', 'ksei_code' => '111'],
      ['id' => '37', 'name' => 'BPD YOGYAKARTA', 'ksei_code' => '112'],
      ['id' => '38', 'name' => 'BPD JAWA TENGAH', 'ksei_code' => '113'],
      ['id' => '39', 'name' => 'BPD JAWA TIMUR', 'ksei_code' => '114'],
      ['id' => '40', 'name' => 'BPD JAMBI', 'ksei_code' => '115'],
      ['id' => '41', 'name' => 'BPD ACEH', 'ksei_code' => '116'],
      ['id' => '42', 'name' => 'BPD SUMATERA UTARA', 'ksei_code' => '117'],
      ['id' => '43', 'name' => 'BANK NAGARI', 'ksei_code' => '118'],
      ['id' => '44', 'name' => 'BPD RIAU', 'ksei_code' => '119'],
      ['id' => '45', 'name' => 'BPD SUMSEL DAN BABEL', 'ksei_code' => '120'],
      ['id' => '46', 'name' => 'BPD LAMPUNG', 'ksei_code' => '121'],
      ['id' => '47', 'name' => 'BPD KALIMANTAN SELATAN', 'ksei_code' => '122'],
      ['id' => '48', 'name' => 'BPD KALIMANTAN BARAT', 'ksei_code' => '123'],
      ['id' => '49', 'name' => 'BPD KALIMANTAN TIMUR DAN KALIMANTAN UTARA', 'ksei_code' => '124'],
      ['id' => '50', 'name' => 'BPD KALIMANTAN TENGAH', 'ksei_code' => '125'],
      ['id' => '51', 'name' => 'BPD SULAWESI SELATAN BARAT', 'ksei_code' => '126'],
      ['id' => '52', 'name' => 'BPD SULAWESI UTARA', 'ksei_code' => '127'],
      ['id' => '53', 'name' => 'BPD NUSA TENGGARA BARAT', 'ksei_code' => '128'],
      ['id' => '54', 'name' => 'BPD BALI', 'ksei_code' => '129'],
      ['id' => '55', 'name' => 'BPD NUSA TENGGARA TIMUR', 'ksei_code' => '130'],
      ['id' => '56', 'name' => 'BPD MALUKU', 'ksei_code' => '131'],
      ['id' => '57', 'name' => 'BPD PAPUA', 'ksei_code' => '132'],
      ['id' => '58', 'name' => 'BPD BENGKULU', 'ksei_code' => '133'],
      ['id' => '59', 'name' => 'BPD SULAWESI TENGAH', 'ksei_code' => '134'],
      ['id' => '60', 'name' => 'BPD SULAWESI TENGGARA', 'ksei_code' => '135'],
      ['id' => '61', 'name' => 'BPD BANTEN', 'ksei_code' => '137'],
      ['id' => '62', 'name' => 'BANK NUSANTARA PARAHYANGAN', 'ksei_code' => '145'],
      ['id' => '63', 'name' => 'BANK OF INDIA INDONESIA', 'ksei_code' => '146'],
      ['id' => '64', 'name' => 'BANK MUAMALAT INDONESIA', 'ksei_code' => '147'],
      ['id' => '65', 'name' => 'BANK MESTIKA DHARMA', 'ksei_code' => '151'],
      ['id' => '66', 'name' => 'BANK SHINHAN INDONESIA', 'ksei_code' => '152'],
      ['id' => '67', 'name' => 'BANK SINARMAS', 'ksei_code' => '153'],
      ['id' => '68', 'name' => 'BANK MASPION INDONESIA', 'ksei_code' => '157'],
      ['id' => '69', 'name' => 'BANK GANESHA', 'ksei_code' => '161'],
      ['id' => '70', 'name' => 'BANK ICBC INDONESIA', 'ksei_code' => '164'],
      ['id' => '71', 'name' => 'BANK QNB INDONESIA', 'ksei_code' => '167'],
      ['id' => '72', 'name' => 'BANK TABUNGAN NEGARA (PERSERO)', 'ksei_code' => '200'],
      ['id' => '73', 'name' => 'BANK WOORI SAUDARA INDONESIA 1906', 'ksei_code' => '212'],
      ['id' => '74', 'name' => 'BANK TABUNGAN PENSIUNAN NASIONAL', 'ksei_code' => '213'],
      ['id' => '75', 'name' => 'BANK VICTORIA SYARIAH', 'ksei_code' => '405'],
      ['id' => '76', 'name' => 'BANK SYARIAH BRI', 'ksei_code' => '422'],
      ['id' => '77', 'name' => 'BANK JABAR BANTEN SYARIAH', 'ksei_code' => '425'],
      ['id' => '78', 'name' => 'BANK MEGA', 'ksei_code' => '426'],
      ['id' => '79', 'name' => 'BNI SYARIAH', 'ksei_code' => '427'],
      ['id' => '80', 'name' => 'BANK BUKOPIN', 'ksei_code' => '441'],
      ['id' => '81', 'name' => 'BANK SYARIAH MANDIRI', 'ksei_code' => '451'],
      ['id' => '82', 'name' => 'BANK BISNIS INTERNASIONAL', 'ksei_code' => '459'],
      ['id' => '83', 'name' => 'BANK OKE INDONESIA', 'ksei_code' => '466'],
      ['id' => '84', 'name' => 'BANK JASA JAKARTA', 'ksei_code' => '472'],
      ['id' => '85', 'name' => 'BANK KEB HANA INDONESIA', 'ksei_code' => '484'],
      ['id' => '86', 'name' => 'BANK MNC INTERNASIONAL', 'ksei_code' => '485'],
      ['id' => '87', 'name' => 'BANK YUDHA BHAKTI', 'ksei_code' => '490'],
      ['id' => '88', 'name' => 'BANK MITRANIAGA', 'ksei_code' => '491'],
      ['id' => '89', 'name' => 'BANK RAKYAT INDONESIA AGRONIAGA', 'ksei_code' => '494'],
      ['id' => '90', 'name' => 'BANK SBI INDONESIA', 'ksei_code' => '498'],
      ['id' => '91', 'name' => 'BANK ROYAL INDONESIA', 'ksei_code' => '501'],
      ['id' => '92', 'name' => 'BANK NATIONALNOBU', 'ksei_code' => '503'],
      ['id' => '93', 'name' => 'BANK SYARIAH MEGA INDONESIA', 'ksei_code' => '506'],
      ['id' => '94', 'name' => 'BANK INA PERDANA', 'ksei_code' => '513'],
      ['id' => '95', 'name' => 'BANK PANIN DUBAI SYARIAH', 'ksei_code' => '517'],
      ['id' => '96', 'name' => 'PRIMA MASTERBANK', 'ksei_code' => '520'],
      ['id' => '97', 'name' => 'BANK SYARIAH BUKOPIN', 'ksei_code' => '521'],
      ['id' => '98', 'name' => 'BANK SAHABAT SAMPOERNA', 'ksei_code' => '523'],
      ['id' => '99', 'name' => 'BANK DINAR INDONESIA', 'ksei_code' => '526'],
      ['id' => '100', 'name' => 'BANK AMAR INDONESIA', 'ksei_code' => '531'],
      ['id' => '101', 'name' => 'BANK KESEJAHTERAAN EKONOMI', 'ksei_code' => '535'],
      ['id' => '102', 'name' => 'BANK BCA SYARIAH', 'ksei_code' => '536'],
      ['id' => '103', 'name' => 'BANK ARTOS INDONESIA', 'ksei_code' => '542'],
      ['id' => '104', 'name' => 'BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH', 'ksei_code' => '547'],
      ['id' => '105', 'name' => 'BANK MULTIARTA SENTOSA', 'ksei_code' => '548'],
      ['id' => '106', 'name' => 'BANK MAYORA', 'ksei_code' => '553'],
      ['id' => '107', 'name' => 'BANK INDEX SELINDO', 'ksei_code' => '555'],
      ['id' => '108', 'name' => 'CENTRATAMA NASIONALBANK', 'ksei_code' => '559'],
      ['id' => '109', 'name' => 'BANK FAMA INTERNATIONAL', 'ksei_code' => '562'],
      ['id' => '110', 'name' => 'BANK MANDIRI TASPEN POS', 'ksei_code' => '564'],
      ['id' => '111', 'name' => 'BANK VICTORIA INTERNASIONAL', 'ksei_code' => '566'],
      ['id' => '112', 'name' => 'BANK HARDA INTERNASIONAL', 'ksei_code' => '567'],
      ['id' => '113', 'name' => 'BANK PERMATA SYARIAH', 'ksei_code' => '721'],
      ['id' => '114', 'name' => 'BANK DANAMON INDONESIA SYARIAH', 'ksei_code' => '722'],
      ['id' => '115', 'name' => 'BANK TABUNGAN NEGARA (PERSERO) SYARIAH', 'ksei_code' => '723'],
      ['id' => '116', 'name' => 'BANK DKI SYARIAH', 'ksei_code' => '724'],
      ['id' => '117', 'name' => 'BPD JAWA TENGAH SYARIAH', 'ksei_code' => '725'],
      ['id' => '118', 'name' => 'BPD JAWA TIMUR SYARIAH', 'ksei_code' => '726'],
      ['id' => '119', 'name' => 'BPD KALIMANTAN BARAT SYARIAH', 'ksei_code' => '727'],
      ['id' => '120', 'name' => 'BPD KALIMANTAN SELATAN SYARIAH', 'ksei_code' => '728'],
      ['id' => '121', 'name' => 'BPD KALIMANTAN TIMUR DAN KALIMANTAN UTARA SYARIAH', 'ksei_code' => '729'],
      ['id' => '122', 'name' => 'BANK CIMB NIAGA SYARIAH', 'ksei_code' => '730'],
      ['id' => '123', 'name' => 'BANK OCBC NISP SYARIAH', 'ksei_code' => '731'],
      ['id' => '124', 'name' => 'BPD SUMATERA BARAT SYARIAH', 'ksei_code' => '732'],
      ['id' => '125', 'name' => 'BPD SUMATERA UTARA SYARIAH', 'ksei_code' => '733'],
      ['id' => '126', 'name' => 'BANK SINARMAS SYARIAH', 'ksei_code' => '734'],
      ['id' => '127', 'name' => 'BPD SULAWESI SELATAN BARAT UU SYARIAH', 'ksei_code' => '735'],
      ['id' => '128', 'name' => 'BPD YOGYAKARTA SYARIAH', 'ksei_code' => '736'],
      ['id' => '129', 'name' => 'BANK AGRIS', 'ksei_code' => '945'],
      ['id' => '130', 'name' => 'MAYBANK SYARIAH INDONESIA', 'ksei_code' => '947'],
      ['id' => '131', 'name' => 'BANK CTBC INDONESIA', 'ksei_code' => '949'],
      ['id' => '132', 'name' => 'BANK COMMONWEALTH', 'ksei_code' => '950'],
    ];
    DB::table('banks')->insert($banks);
  }
}
