<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

      //DB::table('cities')->truncate();

      $cities = [
        ['id' => '1101', 'province_id' => '11', 'name' => 'KABUPATEN SIMEULUE', 'ksei_code' => '1 ', 'ksei_name' => 'SIMEULUE '],
        ['id' => '1102', 'province_id' => '11', 'name' => 'KABUPATEN ACEH SINGKIL', 'ksei_code' => '2 ', 'ksei_name' => 'ACEH SINGKIL '],
        ['id' => '1103', 'province_id' => '11', 'name' => 'KABUPATEN ACEH SELATAN', 'ksei_code' => '4 ', 'ksei_name' => 'ACEH SELATAN '],
        ['id' => '1104', 'province_id' => '11', 'name' => 'KABUPATEN ACEH TENGGARA', 'ksei_code' => '5 ', 'ksei_name' => 'ACEH TENGGARA '],
        ['id' => '1105', 'province_id' => '11', 'name' => 'KABUPATEN ACEH TIMUR', 'ksei_code' => '6 ', 'ksei_name' => 'ACEH TIMUR '],
        ['id' => '1106', 'province_id' => '11', 'name' => 'KABUPATEN ACEH TENGAH', 'ksei_code' => '7 ', 'ksei_name' => 'ACEH TENGAH '],
        ['id' => '1107', 'province_id' => '11', 'name' => 'KABUPATEN ACEH BARAT', 'ksei_code' => '8 ', 'ksei_name' => 'ACEH BARAT '],
        ['id' => '1108', 'province_id' => '11', 'name' => 'KABUPATEN ACEH BESAR', 'ksei_code' => '9 ', 'ksei_name' => 'ACEH BESAR '],
        ['id' => '1109', 'province_id' => '11', 'name' => 'KABUPATEN PIDIE', 'ksei_code' => '10 ', 'ksei_name' => 'PIDIE '],
        ['id' => '1110', 'province_id' => '11', 'name' => 'KABUPATEN BIREUEN', 'ksei_code' => '12 ', 'ksei_name' => 'BIREUEN '],
        ['id' => '1111', 'province_id' => '11', 'name' => 'KABUPATEN ACEH UTARA', 'ksei_code' => '13 ', 'ksei_name' => 'ACEH UTARA '],
        ['id' => '1112', 'province_id' => '11', 'name' => 'KABUPATEN ACEH BARAT DAYA', 'ksei_code' => '14 ', 'ksei_name' => 'ACEH BARAT DAYA '],
        ['id' => '1113', 'province_id' => '11', 'name' => 'KABUPATEN GAYO LUES', 'ksei_code' => '15 ', 'ksei_name' => 'GAYO LUES '],
        ['id' => '1114', 'province_id' => '11', 'name' => 'KABUPATEN ACEH TAMIANG', 'ksei_code' => '16 ', 'ksei_name' => 'ACEH TAMIANG '],
        ['id' => '1115', 'province_id' => '11', 'name' => 'KABUPATEN NAGAN RAYA', 'ksei_code' => '17 ', 'ksei_name' => 'NAGAN RAYA '],
        ['id' => '1116', 'province_id' => '11', 'name' => 'KABUPATEN ACEH JAYA', 'ksei_code' => '18 ', 'ksei_name' => 'ACEH JAYA '],
        ['id' => '1117', 'province_id' => '11', 'name' => 'KABUPATEN BENER MERIAH', 'ksei_code' => '19 ', 'ksei_name' => 'BENER MERIAH '],
        ['id' => '1118', 'province_id' => '11', 'name' => 'KABUPATEN PIDIE JAYA', 'ksei_code' => '11 ', 'ksei_name' => 'PIDIE JAYA '],
        ['id' => '1171', 'province_id' => '11', 'name' => 'KOTA BANDA ACEH', 'ksei_code' => '20 ', 'ksei_name' => 'BANDA ACEH '],
        ['id' => '1172', 'province_id' => '11', 'name' => 'KOTA SABANG', 'ksei_code' => '21 ', 'ksei_name' => 'SABANG '],
        ['id' => '1173', 'province_id' => '11', 'name' => 'KOTA LANGSA', 'ksei_code' => '22 ', 'ksei_name' => 'LANGSA '],
        ['id' => '1174', 'province_id' => '11', 'name' => 'KOTA LHOKSEUMAWE', 'ksei_code' => '23 ', 'ksei_name' => 'LHOKSEUMAWE '],
        ['id' => '1175', 'province_id' => '11', 'name' => 'KOTA SUBULUSSALAM', 'ksei_code' => '3 ', 'ksei_name' => 'KOTA SUBULUSSALAM '],
        ['id' => '1201', 'province_id' => '12', 'name' => 'KABUPATEN NIAS', 'ksei_code' => '24 ', 'ksei_name' => 'NIAS '],
        ['id' => '1202', 'province_id' => '12', 'name' => 'KABUPATEN MANDAILING NATAL', 'ksei_code' => '25 ', 'ksei_name' => 'MANDAILING NATAL '],
        ['id' => '1203', 'province_id' => '12', 'name' => 'KABUPATEN TAPANULI SELATAN', 'ksei_code' => '26 ', 'ksei_name' => 'TAPANULI SELATAN '],
        ['id' => '1204', 'province_id' => '12', 'name' => 'KABUPATEN TAPANULI TENGAH', 'ksei_code' => '29 ', 'ksei_name' => 'TAPANULI TENGAH '],
        ['id' => '1205', 'province_id' => '12', 'name' => 'KABUPATEN TAPANULI UTARA', 'ksei_code' => '30 ', 'ksei_name' => 'TAPANULI UTARA '],
        ['id' => '1206', 'province_id' => '12', 'name' => 'KABUPATEN TOBA SAMOSIR', 'ksei_code' => '31 ', 'ksei_name' => 'TOBA SAMOSIR '],
        ['id' => '1207', 'province_id' => '12', 'name' => 'KABUPATEN LABUHAN BATU', 'ksei_code' => '32 ', 'ksei_name' => 'LABUHAN BATU '],
        ['id' => '1208', 'province_id' => '12', 'name' => 'KABUPATEN ASAHAN', 'ksei_code' => '33 ', 'ksei_name' => 'ASAHAN '],
        ['id' => '1209', 'province_id' => '12', 'name' => 'KABUPATEN SIMALUNGUN', 'ksei_code' => '35 ', 'ksei_name' => 'SIMALUNGUN '],
        ['id' => '1210', 'province_id' => '12', 'name' => 'KABUPATEN DAIRI', 'ksei_code' => '36 ', 'ksei_name' => 'DAIRI '],
        ['id' => '1211', 'province_id' => '12', 'name' => 'KABUPATEN KARO', 'ksei_code' => '37 ', 'ksei_name' => 'KARO '],
        ['id' => '1212', 'province_id' => '12', 'name' => 'KABUPATEN DELI SERDANG', 'ksei_code' => '38 ', 'ksei_name' => 'DELI SERDANG '],
        ['id' => '1213', 'province_id' => '12', 'name' => 'KABUPATEN LANGKAT', 'ksei_code' => '39 ', 'ksei_name' => 'LANGKAT '],
        ['id' => '1214', 'province_id' => '12', 'name' => 'KABUPATEN NIAS SELATAN', 'ksei_code' => '40 ', 'ksei_name' => 'NIAS SELATAN '],
        ['id' => '1215', 'province_id' => '12', 'name' => 'KABUPATEN HUMBANG HASUNDUTAN', 'ksei_code' => '41 ', 'ksei_name' => 'HUMBANG HASUNDUTAN '],
        ['id' => '1216', 'province_id' => '12', 'name' => 'KABUPATEN PAKPAK BHARAT', 'ksei_code' => '42 ', 'ksei_name' => 'PAKPAK BHARAT '],
        ['id' => '1217', 'province_id' => '12', 'name' => 'KABUPATEN SAMOSIR', 'ksei_code' => '43 ', 'ksei_name' => 'SAMOSIR '],
        ['id' => '1218', 'province_id' => '12', 'name' => 'KABUPATEN SERDANG BEDAGAI', 'ksei_code' => '44 ', 'ksei_name' => 'SERDANG BEDAGAI '],
        ['id' => '1219', 'province_id' => '12', 'name' => 'KABUPATEN BATU BARA', 'ksei_code' => '34 ', 'ksei_name' => 'BATUBARA '],
        ['id' => '1220', 'province_id' => '12', 'name' => 'KABUPATEN PADANG LAWAS UTARA', 'ksei_code' => '28 ', 'ksei_name' => 'PADANG LAWAS UTARA '],
        ['id' => '1221', 'province_id' => '12', 'name' => 'KABUPATEN PADANG LAWAS', 'ksei_code' => '27 ', 'ksei_name' => 'PADANG LAWAS '],
        ['id' => '1222', 'province_id' => '12', 'name' => 'KABUPATEN LABUHAN BATU SELATAN', 'ksei_code' => '32 ', 'ksei_name' => 'LABUHAN BATU '],
        ['id' => '1223', 'province_id' => '12', 'name' => 'KABUPATEN LABUHAN BATU UTARA', 'ksei_code' => '32 ', 'ksei_name' => 'LABUHAN BATU '],
        ['id' => '1224', 'province_id' => '12', 'name' => 'KABUPATEN NIAS UTARA', 'ksei_code' => '24 ', 'ksei_name' => 'NIAS '],
        ['id' => '1225', 'province_id' => '12', 'name' => 'KABUPATEN NIAS BARAT', 'ksei_code' => '24 ', 'ksei_name' => 'NIAS '],
        ['id' => '1271', 'province_id' => '12', 'name' => 'KOTA SIBOLGA', 'ksei_code' => '45 ', 'ksei_name' => 'SIBOLGA '],
        ['id' => '1272', 'province_id' => '12', 'name' => 'KOTA TANJUNG BALAI', 'ksei_code' => '46 ', 'ksei_name' => 'TANJUNG BALAI '],
        ['id' => '1273', 'province_id' => '12', 'name' => 'KOTA PEMATANG SIANTAR', 'ksei_code' => '47 ', 'ksei_name' => 'PEMATANG SIANTAR '],
        ['id' => '1274', 'province_id' => '12', 'name' => 'KOTA TEBING TINGGI', 'ksei_code' => '48 ', 'ksei_name' => 'TEBING TINGGI '],
        ['id' => '1275', 'province_id' => '12', 'name' => 'KOTA MEDAN', 'ksei_code' => '49 ', 'ksei_name' => 'MEDAN '],
        ['id' => '1276', 'province_id' => '12', 'name' => 'KOTA BINJAI', 'ksei_code' => '50 ', 'ksei_name' => 'BINJAI '],
        ['id' => '1277', 'province_id' => '12', 'name' => 'KOTA PADANGSIDIMPUAN', 'ksei_code' => '51 ', 'ksei_name' => 'PADANG SIDEMPUAN '],
        ['id' => '1278', 'province_id' => '12', 'name' => 'KOTA GUNUNGSITOLI', 'ksei_code' => '24 ', 'ksei_name' => 'NIAS '],
        ['id' => '1301', 'province_id' => '13', 'name' => 'KABUPATEN KEPULAUAN MENTAWAI', 'ksei_code' => '52 ', 'ksei_name' => 'KEPULAUAN MENTAWAI '],
        ['id' => '1302', 'province_id' => '13', 'name' => 'KABUPATEN PESISIR SELATAN', 'ksei_code' => '53 ', 'ksei_name' => 'PESISIR SELATAN '],
        ['id' => '1303', 'province_id' => '13', 'name' => 'KABUPATEN SOLOK', 'ksei_code' => '65 ', 'ksei_name' => 'SOLOK '],
        ['id' => '1304', 'province_id' => '13', 'name' => 'KABUPATEN SIJUNJUNG', 'ksei_code' => '55 ', 'ksei_name' => 'SAWAHLUNTO/SIJUNJUNG '],
        ['id' => '1305', 'province_id' => '13', 'name' => 'KABUPATEN TANAH DATAR', 'ksei_code' => '56 ', 'ksei_name' => 'TANAH DATAR '],
        ['id' => '1306', 'province_id' => '13', 'name' => 'KABUPATEN PADANG PARIAMAN', 'ksei_code' => '57 ', 'ksei_name' => 'PADANG PARIAMAN '],
        ['id' => '1307', 'province_id' => '13', 'name' => 'KABUPATEN AGAM', 'ksei_code' => '58 ', 'ksei_name' => 'AGAM '],
        ['id' => '1308', 'province_id' => '13', 'name' => 'KABUPATEN LIMA PULUH KOTA', 'ksei_code' => '59 ', 'ksei_name' => 'LIMA PULUH KOTO '],
        ['id' => '1309', 'province_id' => '13', 'name' => 'KABUPATEN PASAMAN', 'ksei_code' => '60 ', 'ksei_name' => 'PASAMAN '],
        ['id' => '1310', 'province_id' => '13', 'name' => 'KABUPATEN SOLOK SELATAN', 'ksei_code' => '61 ', 'ksei_name' => 'SOLOK SELATAN '],
        ['id' => '1311', 'province_id' => '13', 'name' => 'KABUPATEN DHARMASRAYA', 'ksei_code' => '62 ', 'ksei_name' => 'DHARMASRAYA '],
        ['id' => '1312', 'province_id' => '13', 'name' => 'KABUPATEN PASAMAN BARAT', 'ksei_code' => '63 ', 'ksei_name' => 'PASAMAN BARAT '],
        ['id' => '1371', 'province_id' => '13', 'name' => 'KOTA PADANG', 'ksei_code' => '64 ', 'ksei_name' => 'PADANG '],
        ['id' => '1372', 'province_id' => '13', 'name' => 'KOTA SOLOK', 'ksei_code' => '65 ', 'ksei_name' => 'SOLOK '],
        ['id' => '1373', 'province_id' => '13', 'name' => 'KOTA SAWAH LUNTO', 'ksei_code' => '66 ', 'ksei_name' => 'SAWAH LUNTO '],
        ['id' => '1374', 'province_id' => '13', 'name' => 'KOTA PADANG PANJANG', 'ksei_code' => '67 ', 'ksei_name' => 'PADANG PANJANG '],
        ['id' => '1375', 'province_id' => '13', 'name' => 'KOTA BUKITTINGGI', 'ksei_code' => '68 ', 'ksei_name' => 'BUKITTINGGI '],
        ['id' => '1376', 'province_id' => '13', 'name' => 'KOTA PAYAKUMBUH', 'ksei_code' => '69 ', 'ksei_name' => 'PAYAKUMBUH '],
        ['id' => '1377', 'province_id' => '13', 'name' => 'KOTA PARIAMAN', 'ksei_code' => '70 ', 'ksei_name' => 'PARIAMAN '],
        ['id' => '1401', 'province_id' => '14', 'name' => 'KABUPATEN KUANTAN SINGINGI', 'ksei_code' => '71 ', 'ksei_name' => 'KUANTAN SINGINGI '],
        ['id' => '1402', 'province_id' => '14', 'name' => 'KABUPATEN INDRAGIRI HULU', 'ksei_code' => '72 ', 'ksei_name' => 'INDRAGIRI HULU '],
        ['id' => '1403', 'province_id' => '14', 'name' => 'KABUPATEN INDRAGIRI HILIR', 'ksei_code' => '73 ', 'ksei_name' => 'INDRAGIRI HILIR '],
        ['id' => '1404', 'province_id' => '14', 'name' => 'KABUPATEN PELALAWAN', 'ksei_code' => '74 ', 'ksei_name' => 'PELALAWAN '],
        ['id' => '1405', 'province_id' => '14', 'name' => 'KABUPATEN S I A K', 'ksei_code' => '75 ', 'ksei_name' => 'SIAK '],
        ['id' => '1406', 'province_id' => '14', 'name' => 'KABUPATEN KAMPAR', 'ksei_code' => '76 ', 'ksei_name' => 'KAMPAR '],
        ['id' => '1407', 'province_id' => '14', 'name' => 'KABUPATEN ROKAN HULU', 'ksei_code' => '77 ', 'ksei_name' => 'ROKAN HULU '],
        ['id' => '1408', 'province_id' => '14', 'name' => 'KABUPATEN BENGKALIS', 'ksei_code' => '78 ', 'ksei_name' => 'BENGKALIS '],
        ['id' => '1409', 'province_id' => '14', 'name' => 'KABUPATEN ROKAN HILIR', 'ksei_code' => '79 ', 'ksei_name' => 'ROKAN HILIR '],
        ['id' => '1410', 'province_id' => '14', 'name' => 'KABUPATEN KEPULAUAN MERANTI', 'ksei_code' => '478 ', 'ksei_name' => 'KEPULAUAN MERANTI '],
        ['id' => '1471', 'province_id' => '14', 'name' => 'KOTA PEKANBARU', 'ksei_code' => '80 ', 'ksei_name' => 'PEKAN BARU '],
        ['id' => '1473', 'province_id' => '14', 'name' => 'KOTA D U M A I', 'ksei_code' => '81 ', 'ksei_name' => 'DUMAI '],
        ['id' => '1501', 'province_id' => '15', 'name' => 'KABUPATEN KERINCI', 'ksei_code' => '82 ', 'ksei_name' => 'KERINCI '],
        ['id' => '1502', 'province_id' => '15', 'name' => 'KABUPATEN MERANGIN', 'ksei_code' => '83 ', 'ksei_name' => 'MERANGIN '],
        ['id' => '1503', 'province_id' => '15', 'name' => 'KABUPATEN SAROLANGUN', 'ksei_code' => '84 ', 'ksei_name' => 'SAROLANGUN '],
        ['id' => '1504', 'province_id' => '15', 'name' => 'KABUPATEN BATANG HARI', 'ksei_code' => '85 ', 'ksei_name' => 'BATANG HARI '],
        ['id' => '1505', 'province_id' => '15', 'name' => 'KABUPATEN MUARO JAMBI', 'ksei_code' => '86 ', 'ksei_name' => 'MUARO JAMBI '],
        ['id' => '1506', 'province_id' => '15', 'name' => 'KABUPATEN TANJUNG JABUNG TIMUR', 'ksei_code' => '87 ', 'ksei_name' => 'TANJUNG JABUNG TIMUR '],
        ['id' => '1507', 'province_id' => '15', 'name' => 'KABUPATEN TANJUNG JABUNG BARAT', 'ksei_code' => '88 ', 'ksei_name' => 'TANJUNG JABUNG BARAT '],
        ['id' => '1508', 'province_id' => '15', 'name' => 'KABUPATEN TEBO', 'ksei_code' => '89 ', 'ksei_name' => 'TEBO '],
        ['id' => '1509', 'province_id' => '15', 'name' => 'KABUPATEN BUNGO', 'ksei_code' => '90 ', 'ksei_name' => 'BUNGO '],
        ['id' => '1571', 'province_id' => '15', 'name' => 'KOTA JAMBI', 'ksei_code' => '91 ', 'ksei_name' => 'JAMBI '],
        ['id' => '1572', 'province_id' => '15', 'name' => 'KOTA SUNGAI PENUH', 'ksei_code' => '82 ', 'ksei_name' => 'KERINCI '],
        ['id' => '1601', 'province_id' => '16', 'name' => 'KABUPATEN OGAN KOMERING ULU', 'ksei_code' => '92 ', 'ksei_name' => 'OGAN KOMERING ULU '],
        ['id' => '1602', 'province_id' => '16', 'name' => 'KABUPATEN OGAN KOMERING ILIR', 'ksei_code' => '93 ', 'ksei_name' => 'OGAN KOMERING ILIR '],
        ['id' => '1603', 'province_id' => '16', 'name' => 'KABUPATEN MUARA ENIM', 'ksei_code' => '94 ', 'ksei_name' => 'MUARA ENIM '],
        ['id' => '1604', 'province_id' => '16', 'name' => 'KABUPATEN LAHAT', 'ksei_code' => '95 ', 'ksei_name' => 'LAHAT '],
        ['id' => '1605', 'province_id' => '16', 'name' => 'KABUPATEN MUSI RAWAS', 'ksei_code' => '96 ', 'ksei_name' => 'MUSI RAWAS '],
        ['id' => '1606', 'province_id' => '16', 'name' => 'KABUPATEN MUSI BANYUASIN', 'ksei_code' => '97 ', 'ksei_name' => 'MUSI BANYU ASIN '],
        ['id' => '1607', 'province_id' => '16', 'name' => 'KABUPATEN BANYU ASIN', 'ksei_code' => '98 ', 'ksei_name' => 'BANYU ASIN '],
        ['id' => '1608', 'province_id' => '16', 'name' => 'KABUPATEN OGAN KOMERING ULU SELATAN', 'ksei_code' => '99 ', 'ksei_name' => 'OGAN KOMERING ULU SELATAN '],
        ['id' => '1609', 'province_id' => '16', 'name' => 'KABUPATEN OGAN KOMERING ULU TIMUR', 'ksei_code' => '100 ', 'ksei_name' => 'OGAN KOMERING ULU TIMUR '],
        ['id' => '1610', 'province_id' => '16', 'name' => 'KABUPATEN OGAN ILIR', 'ksei_code' => '101 ', 'ksei_name' => 'OGAN ILIR '],
        ['id' => '1611', 'province_id' => '16', 'name' => 'KABUPATEN EMPAT LAWANG', 'ksei_code' => '102 ', 'ksei_name' => 'EMPAT LAWANG '],
        ['id' => '1612', 'province_id' => '16', 'name' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR', 'ksei_code' => '94 ', 'ksei_name' => 'MUARA ENIM '],
        ['id' => '1613', 'province_id' => '16', 'name' => 'KABUPATEN MUSI RAWAS UTARA', 'ksei_code' => '96 ', 'ksei_name' => 'MUSI RAWAS '],
        ['id' => '1671', 'province_id' => '16', 'name' => 'KOTA PALEMBANG', 'ksei_code' => '103 ', 'ksei_name' => 'PALEMBANG '],
        ['id' => '1672', 'province_id' => '16', 'name' => 'KOTA PRABUMULIH', 'ksei_code' => '104 ', 'ksei_name' => 'PRABUMULIH '],
        ['id' => '1673', 'province_id' => '16', 'name' => 'KOTA PAGAR ALAM', 'ksei_code' => '105 ', 'ksei_name' => 'PAGAR ALAM '],
        ['id' => '1674', 'province_id' => '16', 'name' => 'KOTA LUBUKLINGGAU', 'ksei_code' => '106 ', 'ksei_name' => 'LUBUKLINGGAU '],
        ['id' => '1701', 'province_id' => '17', 'name' => 'KABUPATEN BENGKULU SELATAN', 'ksei_code' => '107 ', 'ksei_name' => 'BENGKULU SELATAN '],
        ['id' => '1702', 'province_id' => '17', 'name' => 'KABUPATEN REJANG LEBONG', 'ksei_code' => '108 ', 'ksei_name' => 'REJANG LEBONG '],
        ['id' => '1703', 'province_id' => '17', 'name' => 'KABUPATEN BENGKULU UTARA', 'ksei_code' => '109 ', 'ksei_name' => 'BENGKULU UTARA '],
        ['id' => '1704', 'province_id' => '17', 'name' => 'KABUPATEN KAUR', 'ksei_code' => '110 ', 'ksei_name' => 'KAUR '],
        ['id' => '1705', 'province_id' => '17', 'name' => 'KABUPATEN SELUMA', 'ksei_code' => '111 ', 'ksei_name' => 'SELUMA '],
        ['id' => '1706', 'province_id' => '17', 'name' => 'KABUPATEN MUKOMUKO', 'ksei_code' => '112 ', 'ksei_name' => 'MUKOMUKO '],
        ['id' => '1707', 'province_id' => '17', 'name' => 'KABUPATEN LEBONG', 'ksei_code' => '113 ', 'ksei_name' => 'LEBONG '],
        ['id' => '1708', 'province_id' => '17', 'name' => 'KABUPATEN KEPAHIANG', 'ksei_code' => '114 ', 'ksei_name' => 'KEPAHIANG '],
        ['id' => '1709', 'province_id' => '17', 'name' => 'KABUPATEN BENGKULU TENGAH', 'ksei_code' => '115 ', 'ksei_name' => 'BENGKULU '],
        ['id' => '1771', 'province_id' => '17', 'name' => 'KOTA BENGKULU', 'ksei_code' => '115 ', 'ksei_name' => 'BENGKULU '],
        ['id' => '1801', 'province_id' => '18', 'name' => 'KABUPATEN LAMPUNG BARAT', 'ksei_code' => '116 ', 'ksei_name' => 'LAMPUNG BARAT '],
        ['id' => '1802', 'province_id' => '18', 'name' => 'KABUPATEN TANGGAMUS', 'ksei_code' => '117 ', 'ksei_name' => 'TANGGAMUS '],
        ['id' => '1803', 'province_id' => '18', 'name' => 'KABUPATEN LAMPUNG SELATAN', 'ksei_code' => '118 ', 'ksei_name' => 'LAMPUNG SELATAN '],
        ['id' => '1804', 'province_id' => '18', 'name' => 'KABUPATEN LAMPUNG TIMUR', 'ksei_code' => '119 ', 'ksei_name' => 'LAMPUNG TIMUR '],
        ['id' => '1805', 'province_id' => '18', 'name' => 'KABUPATEN LAMPUNG TENGAH', 'ksei_code' => '120 ', 'ksei_name' => 'LAMPUNG TENGAH '],
        ['id' => '1806', 'province_id' => '18', 'name' => 'KABUPATEN LAMPUNG UTARA', 'ksei_code' => '121 ', 'ksei_name' => 'LAMPUNG UTARA '],
        ['id' => '1807', 'province_id' => '18', 'name' => 'KABUPATEN WAY KANAN', 'ksei_code' => '122 ', 'ksei_name' => 'WAY KANAN '],
        ['id' => '1808', 'province_id' => '18', 'name' => 'KABUPATEN TULANGBAWANG', 'ksei_code' => '123 ', 'ksei_name' => 'TULANGBAWANG '],
        ['id' => '1809', 'province_id' => '18', 'name' => 'KABUPATEN PESAWARAN', 'ksei_code' => '124 ', 'ksei_name' => 'PESAWARAN '],
        ['id' => '1810', 'province_id' => '18', 'name' => 'KABUPATEN PRINGSEWU', 'ksei_code' => '477 ', 'ksei_name' => 'PRINGSEWU '],
        ['id' => '1811', 'province_id' => '18', 'name' => 'KABUPATEN MESUJI', 'ksei_code' => '476 ', 'ksei_name' => 'MESUJI '],
        ['id' => '1812', 'province_id' => '18', 'name' => 'KABUPATEN TULANG BAWANG BARAT', 'ksei_code' => '123 ', 'ksei_name' => 'TULANGBAWANG '],
        ['id' => '1813', 'province_id' => '18', 'name' => 'KABUPATEN PESISIR BARAT', 'ksei_code' => '116 ', 'ksei_name' => 'LAMPUNG BARAT '],
        ['id' => '1871', 'province_id' => '18', 'name' => 'KOTA BANDAR LAMPUNG', 'ksei_code' => '125 ', 'ksei_name' => 'BANDAR LAMPUNG '],
        ['id' => '1872', 'province_id' => '18', 'name' => 'KOTA METRO', 'ksei_code' => '126 ', 'ksei_name' => 'METRO '],
        ['id' => '1901', 'province_id' => '19', 'name' => 'KABUPATEN BANGKA', 'ksei_code' => '127 ', 'ksei_name' => 'BANGKA '],
        ['id' => '1902', 'province_id' => '19', 'name' => 'KABUPATEN BELITUNG', 'ksei_code' => '128 ', 'ksei_name' => 'BELITUNG '],
        ['id' => '1903', 'province_id' => '19', 'name' => 'KABUPATEN BANGKA BARAT', 'ksei_code' => '129 ', 'ksei_name' => 'BANGKA BARAT '],
        ['id' => '1904', 'province_id' => '19', 'name' => 'KABUPATEN BANGKA TENGAH', 'ksei_code' => '130 ', 'ksei_name' => 'BANGKA TENGAH '],
        ['id' => '1905', 'province_id' => '19', 'name' => 'KABUPATEN BANGKA SELATAN', 'ksei_code' => '131 ', 'ksei_name' => 'BANGKA SELATAN '],
        ['id' => '1906', 'province_id' => '19', 'name' => 'KABUPATEN BELITUNG TIMUR', 'ksei_code' => '132 ', 'ksei_name' => 'BELITUNG TIMUR '],
        ['id' => '1971', 'province_id' => '19', 'name' => 'KOTA PANGKAL PINANG', 'ksei_code' => '133 ', 'ksei_name' => 'PANGKAL PINANG '],
        ['id' => '2101', 'province_id' => '21', 'name' => 'KABUPATEN KARIMUN', 'ksei_code' => '134 ', 'ksei_name' => 'KARIMUN '],
        ['id' => '2102', 'province_id' => '21', 'name' => 'KABUPATEN BINTAN', 'ksei_code' => '135 ', 'ksei_name' => 'BINTAN '],
        ['id' => '2103', 'province_id' => '21', 'name' => 'KABUPATEN NATUNA', 'ksei_code' => '136 ', 'ksei_name' => 'NATUNA '],
        ['id' => '2104', 'province_id' => '21', 'name' => 'KABUPATEN LINGGA', 'ksei_code' => '137 ', 'ksei_name' => 'LINGGA '],
        ['id' => '2105', 'province_id' => '21', 'name' => 'KABUPATEN KEPULAUAN ANAMBAS', 'ksei_code' => '999 ', 'ksei_name' => 'OTHERS '],
        ['id' => '2171', 'province_id' => '21', 'name' => 'KOTA BATAM', 'ksei_code' => '138 ', 'ksei_name' => 'BATAM '],
        ['id' => '2172', 'province_id' => '21', 'name' => 'KOTA TANJUNG PINANG', 'ksei_code' => '139 ', 'ksei_name' => 'TANJUNG PINANG '],
        ['id' => '3101', 'province_id' => '31', 'name' => 'KABUPATEN KEPULAUAN SERIBU', 'ksei_code' => '140 ', 'ksei_name' => 'KEPULAUAN SERIBU '],
        ['id' => '3171', 'province_id' => '31', 'name' => 'KOTA JAKARTA SELATAN', 'ksei_code' => '141 ', 'ksei_name' => 'JAKARTA SELATAN '],
        ['id' => '3172', 'province_id' => '31', 'name' => 'KOTA JAKARTA TIMUR', 'ksei_code' => '142 ', 'ksei_name' => 'JAKARTA TIMUR '],
        ['id' => '3173', 'province_id' => '31', 'name' => 'KOTA JAKARTA PUSAT', 'ksei_code' => '143 ', 'ksei_name' => 'JAKARTA PUSAT '],
        ['id' => '3174', 'province_id' => '31', 'name' => 'KOTA JAKARTA BARAT', 'ksei_code' => '144 ', 'ksei_name' => 'JAKARTA BARAT '],
        ['id' => '3175', 'province_id' => '31', 'name' => 'KOTA JAKARTA UTARA', 'ksei_code' => '145 ', 'ksei_name' => 'JAKARTA UTARA '],
        ['id' => '3201', 'province_id' => '32', 'name' => 'KABUPATEN BOGOR', 'ksei_code' => '146 ', 'ksei_name' => 'BOGOR '],
        ['id' => '3202', 'province_id' => '32', 'name' => 'KABUPATEN SUKABUMI', 'ksei_code' => '147 ', 'ksei_name' => 'SUKABUMI '],
        ['id' => '3203', 'province_id' => '32', 'name' => 'KABUPATEN CIANJUR', 'ksei_code' => '148 ', 'ksei_name' => 'CIANJUR '],
        ['id' => '3204', 'province_id' => '32', 'name' => 'KABUPATEN BANDUNG', 'ksei_code' => '149 ', 'ksei_name' => 'BANDUNG '],
        ['id' => '3205', 'province_id' => '32', 'name' => 'KABUPATEN GARUT', 'ksei_code' => '150 ', 'ksei_name' => 'GARUT '],
        ['id' => '3206', 'province_id' => '32', 'name' => 'KABUPATEN TASIKMALAYA', 'ksei_code' => '151 ', 'ksei_name' => 'TASIKMALAYA '],
        ['id' => '3207', 'province_id' => '32', 'name' => 'KABUPATEN CIAMIS', 'ksei_code' => '152 ', 'ksei_name' => 'CIAMIS '],
        ['id' => '3208', 'province_id' => '32', 'name' => 'KABUPATEN KUNINGAN', 'ksei_code' => '153 ', 'ksei_name' => 'KUNINGAN '],
        ['id' => '3209', 'province_id' => '32', 'name' => 'KABUPATEN CIREBON', 'ksei_code' => '154 ', 'ksei_name' => 'CIREBON '],
        ['id' => '3210', 'province_id' => '32', 'name' => 'KABUPATEN MAJALENGKA', 'ksei_code' => '155 ', 'ksei_name' => 'MAJALENGKA '],
        ['id' => '3211', 'province_id' => '32', 'name' => 'KABUPATEN SUMEDANG', 'ksei_code' => '156 ', 'ksei_name' => 'SUMEDANG '],
        ['id' => '3212', 'province_id' => '32', 'name' => 'KABUPATEN INDRAMAYU', 'ksei_code' => '157 ', 'ksei_name' => 'INDRAMAYU '],
        ['id' => '3213', 'province_id' => '32', 'name' => 'KABUPATEN SUBANG', 'ksei_code' => '158 ', 'ksei_name' => 'SUBANG '],
        ['id' => '3214', 'province_id' => '32', 'name' => 'KABUPATEN PURWAKARTA', 'ksei_code' => '159 ', 'ksei_name' => 'PURWAKARTA '],
        ['id' => '3215', 'province_id' => '32', 'name' => 'KABUPATEN KARAWANG', 'ksei_code' => '160 ', 'ksei_name' => 'KARAWANG '],
        ['id' => '3216', 'province_id' => '32', 'name' => 'KABUPATEN BEKASI', 'ksei_code' => '161 ', 'ksei_name' => 'BEKASI '],
        ['id' => '3217', 'province_id' => '32', 'name' => 'KABUPATEN BANDUNG BARAT', 'ksei_code' => '149 ', 'ksei_name' => 'BANDUNG '],
        ['id' => '3218', 'province_id' => '32', 'name' => 'KABUPATEN PANGANDARAN', 'ksei_code' => '152 ', 'ksei_name' => 'CIAMIS '],
        ['id' => '3271', 'province_id' => '32', 'name' => 'KOTA BOGOR', 'ksei_code' => '146 ', 'ksei_name' => 'BOGOR '],
        ['id' => '3272', 'province_id' => '32', 'name' => 'KOTA SUKABUMI', 'ksei_code' => '147 ', 'ksei_name' => 'SUKABUMI '],
        ['id' => '3273', 'province_id' => '32', 'name' => 'KOTA BANDUNG', 'ksei_code' => '149 ', 'ksei_name' => 'BANDUNG '],
        ['id' => '3274', 'province_id' => '32', 'name' => 'KOTA CIREBON', 'ksei_code' => '154 ', 'ksei_name' => 'CIREBON '],
        ['id' => '3275', 'province_id' => '32', 'name' => 'KOTA BEKASI', 'ksei_code' => '161 ', 'ksei_name' => 'BEKASI '],
        ['id' => '3276', 'province_id' => '32', 'name' => 'KOTA DEPOK', 'ksei_code' => '167 ', 'ksei_name' => 'DEPOK '],
        ['id' => '3277', 'province_id' => '32', 'name' => 'KOTA CIMAHI', 'ksei_code' => '168 ', 'ksei_name' => 'CIMAHI '],
        ['id' => '3278', 'province_id' => '32', 'name' => 'KOTA TASIKMALAYA', 'ksei_code' => '151 ', 'ksei_name' => 'TASIKMALAYA '],
        ['id' => '3279', 'province_id' => '32', 'name' => 'KOTA BANJAR', 'ksei_code' => '170 ', 'ksei_name' => 'BANJAR - JAWA BARAT '],
        ['id' => '3301', 'province_id' => '33', 'name' => 'KABUPATEN CILACAP', 'ksei_code' => '171 ', 'ksei_name' => 'CILACAP '],
        ['id' => '3302', 'province_id' => '33', 'name' => 'KABUPATEN BANYUMAS', 'ksei_code' => '172 ', 'ksei_name' => 'BANYUMAS '],
        ['id' => '3303', 'province_id' => '33', 'name' => 'KABUPATEN PURBALINGGA', 'ksei_code' => '173 ', 'ksei_name' => 'PURBALINGGA '],
        ['id' => '3304', 'province_id' => '33', 'name' => 'KABUPATEN BANJARNEGARA', 'ksei_code' => '174 ', 'ksei_name' => 'BANJARNEGARA '],
        ['id' => '3305', 'province_id' => '33', 'name' => 'KABUPATEN KEBUMEN', 'ksei_code' => '175 ', 'ksei_name' => 'KEBUMEN '],
        ['id' => '3306', 'province_id' => '33', 'name' => 'KABUPATEN PURWOREJO', 'ksei_code' => '176 ', 'ksei_name' => 'PURWOREJO '],
        ['id' => '3307', 'province_id' => '33', 'name' => 'KABUPATEN WONOSOBO', 'ksei_code' => '177 ', 'ksei_name' => 'WONOSOBO '],
        ['id' => '3308', 'province_id' => '33', 'name' => 'KABUPATEN MAGELANG', 'ksei_code' => '178 ', 'ksei_name' => 'MAGELANG '],
        ['id' => '3309', 'province_id' => '33', 'name' => 'KABUPATEN BOYOLALI', 'ksei_code' => '179 ', 'ksei_name' => 'BOYOLALI '],
        ['id' => '3310', 'province_id' => '33', 'name' => 'KABUPATEN KLATEN', 'ksei_code' => '180 ', 'ksei_name' => 'KLATEN '],
        ['id' => '3311', 'province_id' => '33', 'name' => 'KABUPATEN SUKOHARJO', 'ksei_code' => '181 ', 'ksei_name' => 'SUKOHARJO '],
        ['id' => '3312', 'province_id' => '33', 'name' => 'KABUPATEN WONOGIRI', 'ksei_code' => '182 ', 'ksei_name' => 'WONOGIRI '],
        ['id' => '3313', 'province_id' => '33', 'name' => 'KABUPATEN KARANGANYAR', 'ksei_code' => '183 ', 'ksei_name' => 'KARANGANYAR '],
        ['id' => '3314', 'province_id' => '33', 'name' => 'KABUPATEN SRAGEN', 'ksei_code' => '184 ', 'ksei_name' => 'SRAGEN '],
        ['id' => '3315', 'province_id' => '33', 'name' => 'KABUPATEN GROBOGAN', 'ksei_code' => '185 ', 'ksei_name' => 'GROBOGAN '],
        ['id' => '3316', 'province_id' => '33', 'name' => 'KABUPATEN BLORA', 'ksei_code' => '186 ', 'ksei_name' => 'BLORA '],
        ['id' => '3317', 'province_id' => '33', 'name' => 'KABUPATEN REMBANG', 'ksei_code' => '187 ', 'ksei_name' => 'REMBANG '],
        ['id' => '3318', 'province_id' => '33', 'name' => 'KABUPATEN PATI', 'ksei_code' => '188 ', 'ksei_name' => 'PATI '],
        ['id' => '3319', 'province_id' => '33', 'name' => 'KABUPATEN KUDUS', 'ksei_code' => '189 ', 'ksei_name' => 'KUDUS '],
        ['id' => '3320', 'province_id' => '33', 'name' => 'KABUPATEN JEPARA', 'ksei_code' => '190 ', 'ksei_name' => 'JEPARA '],
        ['id' => '3321', 'province_id' => '33', 'name' => 'KABUPATEN DEMAK', 'ksei_code' => '191 ', 'ksei_name' => 'DEMAK '],
        ['id' => '3322', 'province_id' => '33', 'name' => 'KABUPATEN SEMARANG', 'ksei_code' => '192 ', 'ksei_name' => 'SEMARANG '],
        ['id' => '3323', 'province_id' => '33', 'name' => 'KABUPATEN TEMANGGUNG', 'ksei_code' => '193 ', 'ksei_name' => 'TEMANGGUNG '],
        ['id' => '3324', 'province_id' => '33', 'name' => 'KABUPATEN KENDAL', 'ksei_code' => '194 ', 'ksei_name' => 'KENDAL '],
        ['id' => '3325', 'province_id' => '33', 'name' => 'KABUPATEN BATANG', 'ksei_code' => '195 ', 'ksei_name' => 'BATANG '],
        ['id' => '3326', 'province_id' => '33', 'name' => 'KABUPATEN PEKALONGAN', 'ksei_code' => '204 ', 'ksei_name' => 'PEKALONGAN '],
        ['id' => '3327', 'province_id' => '33', 'name' => 'KABUPATEN PEMALANG', 'ksei_code' => '197 ', 'ksei_name' => 'PEMALANG '],
        ['id' => '3328', 'province_id' => '33', 'name' => 'KABUPATEN TEGAL', 'ksei_code' => '205 ', 'ksei_name' => 'TEGAL '],
        ['id' => '3329', 'province_id' => '33', 'name' => 'KABUPATEN BREBES', 'ksei_code' => '199 ', 'ksei_name' => 'BREBES '],
        ['id' => '3371', 'province_id' => '33', 'name' => 'KOTA MAGELANG', 'ksei_code' => '178 ', 'ksei_name' => 'MAGELANG '],
        ['id' => '3372', 'province_id' => '33', 'name' => 'KOTA SURAKARTA', 'ksei_code' => '201 ', 'ksei_name' => 'SURAKARTA '],
        ['id' => '3373', 'province_id' => '33', 'name' => 'KOTA SALATIGA', 'ksei_code' => '202 ', 'ksei_name' => 'SALATIGA '],
        ['id' => '3374', 'province_id' => '33', 'name' => 'KOTA SEMARANG', 'ksei_code' => '192 ', 'ksei_name' => 'SEMARANG '],
        ['id' => '3375', 'province_id' => '33', 'name' => 'KOTA PEKALONGAN', 'ksei_code' => '204 ', 'ksei_name' => 'PEKALONGAN '],
        ['id' => '3376', 'province_id' => '33', 'name' => 'KOTA TEGAL', 'ksei_code' => '205 ', 'ksei_name' => 'TEGAL '],
        ['id' => '3401', 'province_id' => '34', 'name' => 'KABUPATEN KULON PROGO', 'ksei_code' => '206 ', 'ksei_name' => 'KULON PROGO '],
        ['id' => '3402', 'province_id' => '34', 'name' => 'KABUPATEN BANTUL', 'ksei_code' => '207 ', 'ksei_name' => 'BANTUL '],
        ['id' => '3403', 'province_id' => '34', 'name' => 'KABUPATEN GUNUNG KIDUL', 'ksei_code' => '208 ', 'ksei_name' => 'GUNUNG KIDUL '],
        ['id' => '3404', 'province_id' => '34', 'name' => 'KABUPATEN SLEMAN', 'ksei_code' => '209 ', 'ksei_name' => 'SLEMAN '],
        ['id' => '3471', 'province_id' => '34', 'name' => 'KOTA YOGYAKARTA', 'ksei_code' => '210 ', 'ksei_name' => 'YOGYAKARTA '],
        ['id' => '3501', 'province_id' => '35', 'name' => 'KABUPATEN PACITAN', 'ksei_code' => '211 ', 'ksei_name' => 'PACITAN '],
        ['id' => '3502', 'province_id' => '35', 'name' => 'KABUPATEN PONOROGO', 'ksei_code' => '212 ', 'ksei_name' => 'PONOROGO '],
        ['id' => '3503', 'province_id' => '35', 'name' => 'KABUPATEN TRENGGALEK', 'ksei_code' => '213 ', 'ksei_name' => 'TRENGGALEK '],
        ['id' => '3504', 'province_id' => '35', 'name' => 'KABUPATEN TULUNGAGUNG', 'ksei_code' => '214 ', 'ksei_name' => 'TULUNGAGUNG '],
        ['id' => '3505', 'province_id' => '35', 'name' => 'KABUPATEN BLITAR', 'ksei_code' => '215 ', 'ksei_name' => 'BLITAR '],
        ['id' => '3506', 'province_id' => '35', 'name' => 'KABUPATEN KEDIRI', 'ksei_code' => '240 ', 'ksei_name' => 'KEDIRI '],
        ['id' => '3507', 'province_id' => '35', 'name' => 'KABUPATEN MALANG', 'ksei_code' => '242 ', 'ksei_name' => 'MALANG '],
        ['id' => '3508', 'province_id' => '35', 'name' => 'KABUPATEN LUMAJANG', 'ksei_code' => '218 ', 'ksei_name' => 'LUMAJANG '],
        ['id' => '3509', 'province_id' => '35', 'name' => 'KABUPATEN JEMBER', 'ksei_code' => '219 ', 'ksei_name' => 'JEMBER '],
        ['id' => '3510', 'province_id' => '35', 'name' => 'KABUPATEN BANYUWANGI', 'ksei_code' => '220 ', 'ksei_name' => 'BANYUWANGI '],
        ['id' => '3511', 'province_id' => '35', 'name' => 'KABUPATEN BONDOWOSO', 'ksei_code' => '221 ', 'ksei_name' => 'BONDOWOSO '],
        ['id' => '3512', 'province_id' => '35', 'name' => 'KABUPATEN SITUBONDO', 'ksei_code' => '222 ', 'ksei_name' => 'SITUBONDO '],
        ['id' => '3513', 'province_id' => '35', 'name' => 'KABUPATEN PROBOLINGGO', 'ksei_code' => '223 ', 'ksei_name' => 'PROBOLINGGO '],
        ['id' => '3514', 'province_id' => '35', 'name' => 'KABUPATEN PASURUAN', 'ksei_code' => '244 ', 'ksei_name' => 'PASURUAN '],
        ['id' => '3515', 'province_id' => '35', 'name' => 'KABUPATEN SIDOARJO', 'ksei_code' => '225 ', 'ksei_name' => 'SIDOARJO '],
        ['id' => '3516', 'province_id' => '35', 'name' => 'KABUPATEN MOJOKERTO', 'ksei_code' => '245 ', 'ksei_name' => 'MOJOKERTO '],
        ['id' => '3517', 'province_id' => '35', 'name' => 'KABUPATEN JOMBANG', 'ksei_code' => '227 ', 'ksei_name' => 'JOMBANG '],
        ['id' => '3518', 'province_id' => '35', 'name' => 'KABUPATEN NGANJUK', 'ksei_code' => '228 ', 'ksei_name' => 'NGANJUK '],
        ['id' => '3519', 'province_id' => '35', 'name' => 'KABUPATEN MADIUN', 'ksei_code' => '246 ', 'ksei_name' => 'MADIUN '],
        ['id' => '3520', 'province_id' => '35', 'name' => 'KABUPATEN MAGETAN', 'ksei_code' => '230 ', 'ksei_name' => 'MAGETAN '],
        ['id' => '3521', 'province_id' => '35', 'name' => 'KABUPATEN NGAWI', 'ksei_code' => '231 ', 'ksei_name' => 'NGAWI '],
        ['id' => '3522', 'province_id' => '35', 'name' => 'KABUPATEN BOJONEGORO', 'ksei_code' => '232 ', 'ksei_name' => 'BOJONEGORO '],
        ['id' => '3523', 'province_id' => '35', 'name' => 'KABUPATEN TUBAN', 'ksei_code' => '233 ', 'ksei_name' => 'TUBAN '],
        ['id' => '3524', 'province_id' => '35', 'name' => 'KABUPATEN LAMONGAN', 'ksei_code' => '234 ', 'ksei_name' => 'LAMONGAN '],
        ['id' => '3525', 'province_id' => '35', 'name' => 'KABUPATEN GRESIK', 'ksei_code' => '235 ', 'ksei_name' => 'GRESIK '],
        ['id' => '3526', 'province_id' => '35', 'name' => 'KABUPATEN BANGKALAN', 'ksei_code' => '236 ', 'ksei_name' => 'BANGKALAN '],
        ['id' => '3527', 'province_id' => '35', 'name' => 'KABUPATEN SAMPANG', 'ksei_code' => '237 ', 'ksei_name' => 'SAMPANG '],
        ['id' => '3528', 'province_id' => '35', 'name' => 'KABUPATEN PAMEKASAN', 'ksei_code' => '238 ', 'ksei_name' => 'PAMEKASAN '],
        ['id' => '3529', 'province_id' => '35', 'name' => 'KABUPATEN SUMENEP', 'ksei_code' => '239 ', 'ksei_name' => 'SUMENEP '],
        ['id' => '3571', 'province_id' => '35', 'name' => 'KOTA KEDIRI', 'ksei_code' => '240 ', 'ksei_name' => 'KEDIRI '],
        ['id' => '3572', 'province_id' => '35', 'name' => 'KOTA BLITAR', 'ksei_code' => '215 ', 'ksei_name' => 'BLITAR '],
        ['id' => '3573', 'province_id' => '35', 'name' => 'KOTA MALANG', 'ksei_code' => '242 ', 'ksei_name' => 'MALANG '],
        ['id' => '3574', 'province_id' => '35', 'name' => 'KOTA PROBOLINGGO', 'ksei_code' => '223 ', 'ksei_name' => 'PROBOLINGGO '],
        ['id' => '3575', 'province_id' => '35', 'name' => 'KOTA PASURUAN', 'ksei_code' => '244 ', 'ksei_name' => 'PASURUAN '],
        ['id' => '3576', 'province_id' => '35', 'name' => 'KOTA MOJOKERTO', 'ksei_code' => '245 ', 'ksei_name' => 'MOJOKERTO '],
        ['id' => '3577', 'province_id' => '35', 'name' => 'KOTA MADIUN', 'ksei_code' => '246 ', 'ksei_name' => 'MADIUN '],
        ['id' => '3578', 'province_id' => '35', 'name' => 'KOTA SURABAYA', 'ksei_code' => '247 ', 'ksei_name' => 'SURABAYA '],
        ['id' => '3579', 'province_id' => '35', 'name' => 'KOTA BATU', 'ksei_code' => '248 ', 'ksei_name' => 'BATU '],
        ['id' => '3601', 'province_id' => '36', 'name' => 'KABUPATEN PANDEGLANG', 'ksei_code' => '249 ', 'ksei_name' => 'PANDEGLANG '],
        ['id' => '3602', 'province_id' => '36', 'name' => 'KABUPATEN LEBAK', 'ksei_code' => '250 ', 'ksei_name' => 'LEBAK '],
        ['id' => '3603', 'province_id' => '36', 'name' => 'KABUPATEN TANGERANG', 'ksei_code' => '253 ', 'ksei_name' => 'TANGERANG '],
        ['id' => '3604', 'province_id' => '36', 'name' => 'KABUPATEN SERANG', 'ksei_code' => '252 ', 'ksei_name' => 'SERANG '],
        ['id' => '3671', 'province_id' => '36', 'name' => 'KOTA TANGERANG', 'ksei_code' => '253 ', 'ksei_name' => 'TANGERANG '],
        ['id' => '3672', 'province_id' => '36', 'name' => 'KOTA CILEGON', 'ksei_code' => '254 ', 'ksei_name' => 'CILEGON '],
        ['id' => '3673', 'province_id' => '36', 'name' => 'KOTA SERANG', 'ksei_code' => '252 ', 'ksei_name' => 'SERANG '],
        ['id' => '3674', 'province_id' => '36', 'name' => 'KOTA TANGERANG SELATAN', 'ksei_code' => '471 ', 'ksei_name' => 'TANGERANG SELATAN '],
        ['id' => '5101', 'province_id' => '51', 'name' => 'KABUPATEN JEMBRANA', 'ksei_code' => '256 ', 'ksei_name' => 'JEMBRANA '],
        ['id' => '5102', 'province_id' => '51', 'name' => 'KABUPATEN TABANAN', 'ksei_code' => '257 ', 'ksei_name' => 'TABANAN '],
        ['id' => '5103', 'province_id' => '51', 'name' => 'KABUPATEN BADUNG', 'ksei_code' => '258 ', 'ksei_name' => 'BADUNG '],
        ['id' => '5104', 'province_id' => '51', 'name' => 'KABUPATEN GIANYAR', 'ksei_code' => '259 ', 'ksei_name' => 'GIANYAR '],
        ['id' => '5105', 'province_id' => '51', 'name' => 'KABUPATEN KLUNGKUNG', 'ksei_code' => '260 ', 'ksei_name' => 'KLUNGKUNG '],
        ['id' => '5106', 'province_id' => '51', 'name' => 'KABUPATEN BANGLI', 'ksei_code' => '261 ', 'ksei_name' => 'BANGLI '],
        ['id' => '5107', 'province_id' => '51', 'name' => 'KABUPATEN KARANG ASEM', 'ksei_code' => '262 ', 'ksei_name' => 'KARANG ASEM '],
        ['id' => '5108', 'province_id' => '51', 'name' => 'KABUPATEN BULELENG', 'ksei_code' => '263 ', 'ksei_name' => 'BULELENG '],
        ['id' => '5171', 'province_id' => '51', 'name' => 'KOTA DENPASAR', 'ksei_code' => '264 ', 'ksei_name' => 'DENPASAR '],
        ['id' => '5201', 'province_id' => '52', 'name' => 'KABUPATEN LOMBOK BARAT', 'ksei_code' => '265 ', 'ksei_name' => 'LOMBOK BARAT '],
        ['id' => '5202', 'province_id' => '52', 'name' => 'KABUPATEN LOMBOK TENGAH', 'ksei_code' => '266 ', 'ksei_name' => 'LOMBOK TENGAH '],
        ['id' => '5203', 'province_id' => '52', 'name' => 'KABUPATEN LOMBOK TIMUR', 'ksei_code' => '267 ', 'ksei_name' => 'LOMBOK TIMUR '],
        ['id' => '5204', 'province_id' => '52', 'name' => 'KABUPATEN SUMBAWA', 'ksei_code' => '268 ', 'ksei_name' => 'SUMBAWA '],
        ['id' => '5205', 'province_id' => '52', 'name' => 'KABUPATEN DOMPU', 'ksei_code' => '269 ', 'ksei_name' => 'DOMPU '],
        ['id' => '5206', 'province_id' => '52', 'name' => 'KABUPATEN BIMA', 'ksei_code' => '273 ', 'ksei_name' => 'BIMA '],
        ['id' => '5207', 'province_id' => '52', 'name' => 'KABUPATEN SUMBAWA BARAT', 'ksei_code' => '271 ', 'ksei_name' => 'SUMBAWA BARAT '],
        ['id' => '5208', 'province_id' => '52', 'name' => 'KABUPATEN LOMBOK UTARA', 'ksei_code' => '265 ', 'ksei_name' => 'LOMBOK BARAT '],
        ['id' => '5271', 'province_id' => '52', 'name' => 'KOTA MATARAM', 'ksei_code' => '272 ', 'ksei_name' => 'MATARAM '],
        ['id' => '5272', 'province_id' => '52', 'name' => 'KOTA BIMA', 'ksei_code' => '273 ', 'ksei_name' => 'BIMA '],
        ['id' => '5301', 'province_id' => '53', 'name' => 'KABUPATEN SUMBA BARAT', 'ksei_code' => '274 ', 'ksei_name' => 'SUMBA BARAT '],
        ['id' => '5302', 'province_id' => '53', 'name' => 'KABUPATEN SUMBA TIMUR', 'ksei_code' => '275 ', 'ksei_name' => 'SUMBA TIMUR '],
        ['id' => '5303', 'province_id' => '53', 'name' => 'KABUPATEN KUPANG', 'ksei_code' => '276 ', 'ksei_name' => 'KUPANG '],
        ['id' => '5304', 'province_id' => '53', 'name' => 'KABUPATEN TIMOR TENGAH SELATAN', 'ksei_code' => '277 ', 'ksei_name' => 'TIMOR TENGAH SELATAN '],
        ['id' => '5305', 'province_id' => '53', 'name' => 'KABUPATEN TIMOR TENGAH UTARA', 'ksei_code' => '278 ', 'ksei_name' => 'TIMOR TENGAH UTARA '],
        ['id' => '5306', 'province_id' => '53', 'name' => 'KABUPATEN BELU', 'ksei_code' => '279 ', 'ksei_name' => 'BELU '],
        ['id' => '5307', 'province_id' => '53', 'name' => 'KABUPATEN ALOR', 'ksei_code' => '280 ', 'ksei_name' => 'ALOR '],
        ['id' => '5308', 'province_id' => '53', 'name' => 'KABUPATEN LEMBATA', 'ksei_code' => '281 ', 'ksei_name' => 'LEMBATA '],
        ['id' => '5309', 'province_id' => '53', 'name' => 'KABUPATEN FLORES TIMUR', 'ksei_code' => '282 ', 'ksei_name' => 'FLORES TIMUR '],
        ['id' => '5310', 'province_id' => '53', 'name' => 'KABUPATEN SIKKA', 'ksei_code' => '283 ', 'ksei_name' => 'SIKKA '],
        ['id' => '5311', 'province_id' => '53', 'name' => 'KABUPATEN ENDE', 'ksei_code' => '284 ', 'ksei_name' => 'ENDE '],
        ['id' => '5312', 'province_id' => '53', 'name' => 'KABUPATEN NGADA', 'ksei_code' => '285 ', 'ksei_name' => 'NGADA '],
        ['id' => '5313', 'province_id' => '53', 'name' => 'KABUPATEN MANGGARAI', 'ksei_code' => '286 ', 'ksei_name' => 'MANGGARAI '],
        ['id' => '5314', 'province_id' => '53', 'name' => 'KABUPATEN ROTE NDAO', 'ksei_code' => '287 ', 'ksei_name' => 'ROTE NDA '],
        ['id' => '5315', 'province_id' => '53', 'name' => 'KABUPATEN MANGGARAI BARAT', 'ksei_code' => '288 ', 'ksei_name' => 'MANGGARAI BARAT '],
        ['id' => '5316', 'province_id' => '53', 'name' => 'KABUPATEN SUMBA TENGAH', 'ksei_code' => '290 ', 'ksei_name' => 'SUMBA TENGAH '],
        ['id' => '5317', 'province_id' => '53', 'name' => 'KABUPATEN SUMBA BARAT DAYA', 'ksei_code' => '289 ', 'ksei_name' => 'SUMBA BARAT DAYA '],
        ['id' => '5318', 'province_id' => '53', 'name' => 'KABUPATEN NAGEKEO', 'ksei_code' => '292 ', 'ksei_name' => 'NAGEKEO '],
        ['id' => '5319', 'province_id' => '53', 'name' => 'KABUPATEN MANGGARAI TIMUR', 'ksei_code' => '291 ', 'ksei_name' => 'MANGGARAI TIMUR '],
        ['id' => '5320', 'province_id' => '53', 'name' => 'KABUPATEN SABU RAIJUA', 'ksei_code' => '276 ', 'ksei_name' => 'KUPANG '],
        ['id' => '5321', 'province_id' => '53', 'name' => 'KABUPATEN MALAKA', 'ksei_code' => '279 ', 'ksei_name' => 'BELU '],
        ['id' => '5371', 'province_id' => '53', 'name' => 'KOTA KUPANG', 'ksei_code' => '276 ', 'ksei_name' => 'KUPANG '],
        ['id' => '6101', 'province_id' => '61', 'name' => 'KABUPATEN SAMBAS', 'ksei_code' => '294 ', 'ksei_name' => 'SAMBAS '],
        ['id' => '6102', 'province_id' => '61', 'name' => 'KABUPATEN BENGKAYANG', 'ksei_code' => '295 ', 'ksei_name' => 'BENGKAYANG '],
        ['id' => '6103', 'province_id' => '61', 'name' => 'KABUPATEN LANDAK', 'ksei_code' => '296 ', 'ksei_name' => 'LANDAK '],
        ['id' => '6104', 'province_id' => '61', 'name' => 'KABUPATEN MEMPAWAH', 'ksei_code' => '306 ', 'ksei_name' => 'PONTIANAK '],
        ['id' => '6105', 'province_id' => '61', 'name' => 'KABUPATEN SANGGAU', 'ksei_code' => '298 ', 'ksei_name' => 'SANGGAU '],
        ['id' => '6106', 'province_id' => '61', 'name' => 'KABUPATEN KETAPANG', 'ksei_code' => '299 ', 'ksei_name' => 'KETAPANG '],
        ['id' => '6107', 'province_id' => '61', 'name' => 'KABUPATEN SINTANG', 'ksei_code' => '300 ', 'ksei_name' => 'SINTANG '],
        ['id' => '6108', 'province_id' => '61', 'name' => 'KABUPATEN KAPUAS HULU', 'ksei_code' => '301 ', 'ksei_name' => 'KAPUAS HULU '],
        ['id' => '6109', 'province_id' => '61', 'name' => 'KABUPATEN SEKADAU', 'ksei_code' => '302 ', 'ksei_name' => 'SEKADAU '],
        ['id' => '6110', 'province_id' => '61', 'name' => 'KABUPATEN MELAWI', 'ksei_code' => '303 ', 'ksei_name' => 'MELAWI '],
        ['id' => '6111', 'province_id' => '61', 'name' => 'KABUPATEN KAYONG UTARA', 'ksei_code' => '305 ', 'ksei_name' => 'KAYONG UTARA '],
        ['id' => '6112', 'province_id' => '61', 'name' => 'KABUPATEN KUBU RAYA', 'ksei_code' => '304 ', 'ksei_name' => 'KUBU RAYA '],
        ['id' => '6171', 'province_id' => '61', 'name' => 'KOTA PONTIANAK', 'ksei_code' => '306 ', 'ksei_name' => 'PONTIANAK '],
        ['id' => '6172', 'province_id' => '61', 'name' => 'KOTA SINGKAWANG', 'ksei_code' => '307 ', 'ksei_name' => 'SINGKAWANG '],
        ['id' => '6201', 'province_id' => '62', 'name' => 'KABUPATEN KOTAWARINGIN BARAT', 'ksei_code' => '308 ', 'ksei_name' => 'KOTAWARINGIN BARAT '],
        ['id' => '6202', 'province_id' => '62', 'name' => 'KABUPATEN KOTAWARINGIN TIMUR', 'ksei_code' => '309 ', 'ksei_name' => 'KOTAWARINGIN TIMUR '],
        ['id' => '6203', 'province_id' => '62', 'name' => 'KABUPATEN KAPUAS', 'ksei_code' => '310 ', 'ksei_name' => 'KAPUAS '],
        ['id' => '6204', 'province_id' => '62', 'name' => 'KABUPATEN BARITO SELATAN', 'ksei_code' => '311 ', 'ksei_name' => 'BARITO SELATAN '],
        ['id' => '6205', 'province_id' => '62', 'name' => 'KABUPATEN BARITO UTARA', 'ksei_code' => '312 ', 'ksei_name' => 'BARITO UTARA '],
        ['id' => '6206', 'province_id' => '62', 'name' => 'KABUPATEN SUKAMARA', 'ksei_code' => '313 ', 'ksei_name' => 'SUKAMARA '],
        ['id' => '6207', 'province_id' => '62', 'name' => 'KABUPATEN LAMANDAU', 'ksei_code' => '314 ', 'ksei_name' => 'LAMANDAU '],
        ['id' => '6208', 'province_id' => '62', 'name' => 'KABUPATEN SERUYAN', 'ksei_code' => '315 ', 'ksei_name' => 'SERUYAN '],
        ['id' => '6209', 'province_id' => '62', 'name' => 'KABUPATEN KATINGAN', 'ksei_code' => '316 ', 'ksei_name' => 'KATINGAN '],
        ['id' => '6210', 'province_id' => '62', 'name' => 'KABUPATEN PULANG PISAU', 'ksei_code' => '317 ', 'ksei_name' => 'PULANG PISAU '],
        ['id' => '6211', 'province_id' => '62', 'name' => 'KABUPATEN GUNUNG MAS', 'ksei_code' => '318 ', 'ksei_name' => 'GUNUNG MAS '],
        ['id' => '6212', 'province_id' => '62', 'name' => 'KABUPATEN BARITO TIMUR', 'ksei_code' => '319 ', 'ksei_name' => 'BARITO TIMUR '],
        ['id' => '6213', 'province_id' => '62', 'name' => 'KABUPATEN MURUNG RAYA', 'ksei_code' => '320 ', 'ksei_name' => 'MURUNG RAYA '],
        ['id' => '6271', 'province_id' => '62', 'name' => 'KOTA PALANGKA RAYA', 'ksei_code' => '321 ', 'ksei_name' => 'PALANGKA RAYA '],
        ['id' => '6301', 'province_id' => '63', 'name' => 'KABUPATEN TANAH LAUT', 'ksei_code' => '322 ', 'ksei_name' => 'TANAH LAUT '],
        ['id' => '6302', 'province_id' => '63', 'name' => 'KABUPATEN KOTA BARU', 'ksei_code' => '323 ', 'ksei_name' => 'KOTA BARU '],
        ['id' => '6303', 'province_id' => '63', 'name' => 'KABUPATEN BANJAR', 'ksei_code' => '473 ', 'ksei_name' => 'BANJAR - KALIMANTAN SELATAN '],
        ['id' => '6304', 'province_id' => '63', 'name' => 'KABUPATEN BARITO KUALA', 'ksei_code' => '325 ', 'ksei_name' => 'BARITO KUALA '],
        ['id' => '6305', 'province_id' => '63', 'name' => 'KABUPATEN TAPIN', 'ksei_code' => '326 ', 'ksei_name' => 'TAPIN '],
        ['id' => '6306', 'province_id' => '63', 'name' => 'KABUPATEN HULU SUNGAI SELATAN', 'ksei_code' => '327 ', 'ksei_name' => 'HULU SUNGAI SELATAN '],
        ['id' => '6307', 'province_id' => '63', 'name' => 'KABUPATEN HULU SUNGAI TENGAH', 'ksei_code' => '328 ', 'ksei_name' => 'HULU SUNGAI TENGAH '],
        ['id' => '6308', 'province_id' => '63', 'name' => 'KABUPATEN HULU SUNGAI UTARA', 'ksei_code' => '329 ', 'ksei_name' => 'HULU SUNGAI UTARA '],
        ['id' => '6309', 'province_id' => '63', 'name' => 'KABUPATEN TABALONG', 'ksei_code' => '330 ', 'ksei_name' => 'TABALONG '],
        ['id' => '6310', 'province_id' => '63', 'name' => 'KABUPATEN TANAH BUMBU', 'ksei_code' => '331 ', 'ksei_name' => 'TANAH BUMBU '],
        ['id' => '6311', 'province_id' => '63', 'name' => 'KABUPATEN BALANGAN', 'ksei_code' => '332 ', 'ksei_name' => 'BALANGAN '],
        ['id' => '6371', 'province_id' => '63', 'name' => 'KOTA BANJARMASIN', 'ksei_code' => '333 ', 'ksei_name' => 'BANJARMASIN '],
        ['id' => '6372', 'province_id' => '63', 'name' => 'KOTA BANJAR BARU', 'ksei_code' => '334 ', 'ksei_name' => 'BANJAR BARU '],
        ['id' => '6401', 'province_id' => '64', 'name' => 'KABUPATEN PASER', 'ksei_code' => '335 ', 'ksei_name' => 'PASIR '],
        ['id' => '6402', 'province_id' => '64', 'name' => 'KABUPATEN KUTAI BARAT', 'ksei_code' => '336 ', 'ksei_name' => 'KUTAI BARAT '],
        ['id' => '6403', 'province_id' => '64', 'name' => 'KABUPATEN KUTAI KARTANEGARA', 'ksei_code' => '337 ', 'ksei_name' => 'KUTAI KERTANEGARA '],
        ['id' => '6404', 'province_id' => '64', 'name' => 'KABUPATEN KUTAI TIMUR', 'ksei_code' => '338 ', 'ksei_name' => 'KUTAI TIMUR '],
        ['id' => '6405', 'province_id' => '64', 'name' => 'KABUPATEN BERAU', 'ksei_code' => '339 ', 'ksei_name' => 'BERAU '],
        ['id' => '6409', 'province_id' => '64', 'name' => 'KABUPATEN PENAJAM PASER UTARA', 'ksei_code' => '343 ', 'ksei_name' => 'PENAJAM PASER UTARA '],
        ['id' => '6411', 'province_id' => '64', 'name' => 'KABUPATEN MAHAKAM HULU', 'ksei_code' => '336 ', 'ksei_name' => 'KUTAI BARAT '],
        ['id' => '6471', 'province_id' => '64', 'name' => 'KOTA BALIKPAPAN', 'ksei_code' => '345 ', 'ksei_name' => 'BALIKPAPAN '],
        ['id' => '6472', 'province_id' => '64', 'name' => 'KOTA SAMARINDA', 'ksei_code' => '346 ', 'ksei_name' => 'SAMARINDA '],
        ['id' => '6474', 'province_id' => '64', 'name' => 'KOTA BONTANG', 'ksei_code' => '348 ', 'ksei_name' => 'BONTANG '],
        ['id' => '6501', 'province_id' => '65', 'name' => 'KABUPATEN MALINAU', 'ksei_code' => '340 ', 'ksei_name' => 'MALINAU '],
        ['id' => '6502', 'province_id' => '65', 'name' => 'KABUPATEN BULUNGAN', 'ksei_code' => '475 ', 'ksei_name' => 'BULUNGAN '],
        ['id' => '6503', 'province_id' => '65', 'name' => 'KABUPATEN TANA TIDUNG', 'ksei_code' => '344 ', 'ksei_name' => 'TANA TIDUNG '],
        ['id' => '6504', 'province_id' => '65', 'name' => 'KABUPATEN NUNUKAN', 'ksei_code' => '342 ', 'ksei_name' => 'NUNUKAN '],
        ['id' => '6571', 'province_id' => '65', 'name' => 'KOTA TARAKAN', 'ksei_code' => '347 ', 'ksei_name' => 'TARAKAN '],
        ['id' => '7101', 'province_id' => '71', 'name' => 'KABUPATEN BOLAANG MONGONDOW', 'ksei_code' => '349 ', 'ksei_name' => 'BOLAANG MONGONDOW '],
        ['id' => '7102', 'province_id' => '71', 'name' => 'KABUPATEN MINAHASA', 'ksei_code' => '350 ', 'ksei_name' => 'MINAHASA '],
        ['id' => '7103', 'province_id' => '71', 'name' => 'KABUPATEN KEPULAUAN SANGIHE', 'ksei_code' => '351 ', 'ksei_name' => 'KEPULAUAN SANGIHE '],
        ['id' => '7104', 'province_id' => '71', 'name' => 'KABUPATEN KEPULAUAN TALAUD', 'ksei_code' => '352 ', 'ksei_name' => 'KEPULAUAN TALAUD '],
        ['id' => '7105', 'province_id' => '71', 'name' => 'KABUPATEN MINAHASA SELATAN', 'ksei_code' => '353 ', 'ksei_name' => 'MINAHASA SELATAN '],
        ['id' => '7106', 'province_id' => '71', 'name' => 'KABUPATEN MINAHASA UTARA', 'ksei_code' => '354 ', 'ksei_name' => 'MINAHASA UTARA '],
        ['id' => '7107', 'province_id' => '71', 'name' => 'KABUPATEN BOLAANG MONGONDOW UTARA', 'ksei_code' => '357 ', 'ksei_name' => 'BOLAANG MANGONDOW UTARA '],
        ['id' => '7108', 'province_id' => '71', 'name' => 'KABUPATEN SIAU TAGULANDANG BIARO', 'ksei_code' => '356 ', 'ksei_name' => 'KEP. SIAU TAGULANDANG BIARO '],
        ['id' => '7109', 'province_id' => '71', 'name' => 'KABUPATEN MINAHASA TENGGARA', 'ksei_code' => '355 ', 'ksei_name' => 'MINAHASA TENGGARA '],
        ['id' => '7110', 'province_id' => '71', 'name' => 'KABUPATEN BOLAANG MONGONDOW SELATAN', 'ksei_code' => '349 ', 'ksei_name' => 'BOLAANG MONGONDOW '],
        ['id' => '7111', 'province_id' => '71', 'name' => 'KABUPATEN BOLAANG MONGONDOW TIMUR', 'ksei_code' => '349 ', 'ksei_name' => 'BOLAANG MONGONDOW '],
        ['id' => '7171', 'province_id' => '71', 'name' => 'KOTA MANADO', 'ksei_code' => '359 ', 'ksei_name' => 'MANADO '],
        ['id' => '7172', 'province_id' => '71', 'name' => 'KOTA BITUNG', 'ksei_code' => '360 ', 'ksei_name' => 'BITUNG '],
        ['id' => '7173', 'province_id' => '71', 'name' => 'KOTA TOMOHON', 'ksei_code' => '361 ', 'ksei_name' => 'TOMOHON '],
        ['id' => '7174', 'province_id' => '71', 'name' => 'KOTA KOTAMOBAGU', 'ksei_code' => '358 ', 'ksei_name' => 'KOTAMOBAGU '],
        ['id' => '7201', 'province_id' => '72', 'name' => 'KABUPATEN BANGGAI KEPULAUAN', 'ksei_code' => '362 ', 'ksei_name' => 'BANGGAI KEPULAUAN '],
        ['id' => '7202', 'province_id' => '72', 'name' => 'KABUPATEN BANGGAI', 'ksei_code' => '363 ', 'ksei_name' => 'BANGGAI '],
        ['id' => '7203', 'province_id' => '72', 'name' => 'KABUPATEN MOROWALI', 'ksei_code' => '364 ', 'ksei_name' => 'MOROWALI '],
        ['id' => '7204', 'province_id' => '72', 'name' => 'KABUPATEN POSO', 'ksei_code' => '365 ', 'ksei_name' => 'POSO '],
        ['id' => '7205', 'province_id' => '72', 'name' => 'KABUPATEN DONGGALA', 'ksei_code' => '366 ', 'ksei_name' => 'DONGGALA '],
        ['id' => '7206', 'province_id' => '72', 'name' => 'KABUPATEN TOLI-TOLI', 'ksei_code' => '367 ', 'ksei_name' => 'TOLI-TOLI '],
        ['id' => '7207', 'province_id' => '72', 'name' => 'KABUPATEN BUOL', 'ksei_code' => '368 ', 'ksei_name' => 'BUOL '],
        ['id' => '7208', 'province_id' => '72', 'name' => 'KABUPATEN PARIGI MOUTONG', 'ksei_code' => '472 ', 'ksei_name' => 'PARIGI MOUTONG '],
        ['id' => '7209', 'province_id' => '72', 'name' => 'KABUPATEN TOJO UNA-UNA', 'ksei_code' => '370 ', 'ksei_name' => 'TOJO UNA-UNA '],
        ['id' => '7210', 'province_id' => '72', 'name' => 'KABUPATEN SIGI', 'ksei_code' => '474 ', 'ksei_name' => 'SIGI'],
        ['id' => '7211', 'province_id' => '72', 'name' => 'KABUPATEN BANGGAI LAUT', 'ksei_code' => '362 ', 'ksei_name' => 'BANGGAI KEPULAUAN '],
        ['id' => '7212', 'province_id' => '72', 'name' => 'KABUPATEN MOROWALI UTARA', 'ksei_code' => '364 ', 'ksei_name' => 'MOROWALI '],
        ['id' => '7271', 'province_id' => '72', 'name' => 'KOTA PALU', 'ksei_code' => '371 ', 'ksei_name' => 'PALU '],
        ['id' => '7301', 'province_id' => '73', 'name' => 'KABUPATEN KEPULAUAN SELAYAR', 'ksei_code' => '372 ', 'ksei_name' => 'SELAYAR '],
        ['id' => '7302', 'province_id' => '73', 'name' => 'KABUPATEN BULUKUMBA', 'ksei_code' => '373 ', 'ksei_name' => 'BULUKUMBA '],
        ['id' => '7303', 'province_id' => '73', 'name' => 'KABUPATEN BANTAENG', 'ksei_code' => '374 ', 'ksei_name' => 'BANTAENG '],
        ['id' => '7304', 'province_id' => '73', 'name' => 'KABUPATEN JENEPONTO', 'ksei_code' => '375 ', 'ksei_name' => 'JENEPONTO '],
        ['id' => '7305', 'province_id' => '73', 'name' => 'KABUPATEN TAKALAR', 'ksei_code' => '376 ', 'ksei_name' => 'TAKALAR '],
        ['id' => '7306', 'province_id' => '73', 'name' => 'KABUPATEN GOWA', 'ksei_code' => '377 ', 'ksei_name' => 'GOWA '],
        ['id' => '7307', 'province_id' => '73', 'name' => 'KABUPATEN SINJAI', 'ksei_code' => '378 ', 'ksei_name' => 'SINJAI '],
        ['id' => '7308', 'province_id' => '73', 'name' => 'KABUPATEN MAROS', 'ksei_code' => '379 ', 'ksei_name' => 'MAROS '],
        ['id' => '7309', 'province_id' => '73', 'name' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN', 'ksei_code' => '380 ', 'ksei_name' => 'PANGKAJENE KEPULAUAN '],
        ['id' => '7310', 'province_id' => '73', 'name' => 'KABUPATEN BARRU', 'ksei_code' => '381 ', 'ksei_name' => 'BARRU '],
        ['id' => '7311', 'province_id' => '73', 'name' => 'KABUPATEN BONE', 'ksei_code' => '382 ', 'ksei_name' => 'BONE '],
        ['id' => '7312', 'province_id' => '73', 'name' => 'KABUPATEN SOPPENG', 'ksei_code' => '383 ', 'ksei_name' => 'SOPPENG '],
        ['id' => '7313', 'province_id' => '73', 'name' => 'KABUPATEN WAJO', 'ksei_code' => '384 ', 'ksei_name' => 'WAJO '],
        ['id' => '7314', 'province_id' => '73', 'name' => 'KABUPATEN SIDENRENG RAPPANG', 'ksei_code' => '385 ', 'ksei_name' => 'SIDENRENG RAPPANG '],
        ['id' => '7315', 'province_id' => '73', 'name' => 'KABUPATEN PINRANG', 'ksei_code' => '386 ', 'ksei_name' => 'PINRANG '],
        ['id' => '7316', 'province_id' => '73', 'name' => 'KABUPATEN ENREKANG', 'ksei_code' => '387 ', 'ksei_name' => 'ENREKANG '],
        ['id' => '7317', 'province_id' => '73', 'name' => 'KABUPATEN LUWU', 'ksei_code' => '388 ', 'ksei_name' => 'LUWU '],
        ['id' => '7318', 'province_id' => '73', 'name' => 'KABUPATEN TANA TORAJA', 'ksei_code' => '389 ', 'ksei_name' => 'TANA TORAJA '],
        ['id' => '7322', 'province_id' => '73', 'name' => 'KABUPATEN LUWU UTARA', 'ksei_code' => '390 ', 'ksei_name' => 'LUWU UTARA '],
        ['id' => '7325', 'province_id' => '73', 'name' => 'KABUPATEN LUWU TIMUR', 'ksei_code' => '391 ', 'ksei_name' => 'LUWU TIMUR '],
        ['id' => '7326', 'province_id' => '73', 'name' => 'KABUPATEN TORAJA UTARA', 'ksei_code' => '389 ', 'ksei_name' => 'TANA TORAJA '],
        ['id' => '7371', 'province_id' => '73', 'name' => 'KOTA MAKASSAR', 'ksei_code' => '392 ', 'ksei_name' => 'MAKASSAR '],
        ['id' => '7372', 'province_id' => '73', 'name' => 'KOTA PAREPARE', 'ksei_code' => '393 ', 'ksei_name' => 'PARE PARE '],
        ['id' => '7373', 'province_id' => '73', 'name' => 'KOTA PALOPO', 'ksei_code' => '394 ', 'ksei_name' => 'PALOPO '],
        ['id' => '7401', 'province_id' => '74', 'name' => 'KABUPATEN BUTON', 'ksei_code' => '395 ', 'ksei_name' => 'BUTON '],
        ['id' => '7402', 'province_id' => '74', 'name' => 'KABUPATEN MUNA', 'ksei_code' => '396 ', 'ksei_name' => 'MUNA '],
        ['id' => '7403', 'province_id' => '74', 'name' => 'KABUPATEN KONAWE', 'ksei_code' => '397 ', 'ksei_name' => 'KONAWE '],
        ['id' => '7404', 'province_id' => '74', 'name' => 'KABUPATEN KOLAKA', 'ksei_code' => '398 ', 'ksei_name' => 'KOLAKA '],
        ['id' => '7405', 'province_id' => '74', 'name' => 'KABUPATEN KONAWE SELATAN', 'ksei_code' => '399 ', 'ksei_name' => 'KONAWE SELATAN '],
        ['id' => '7406', 'province_id' => '74', 'name' => 'KABUPATEN BOMBANA', 'ksei_code' => '400 ', 'ksei_name' => 'BOMBANA '],
        ['id' => '7407', 'province_id' => '74', 'name' => 'KABUPATEN WAKATOBI', 'ksei_code' => '401 ', 'ksei_name' => 'WAKATOBI '],
        ['id' => '7408', 'province_id' => '74', 'name' => 'KABUPATEN KOLAKA UTARA', 'ksei_code' => '402 ', 'ksei_name' => 'KOLAKA UTARA '],
        ['id' => '7409', 'province_id' => '74', 'name' => 'KABUPATEN BUTON UTARA', 'ksei_code' => '403 ', 'ksei_name' => 'BUTON UTARA '],
        ['id' => '7410', 'province_id' => '74', 'name' => 'KABUPATEN KONAWE UTARA', 'ksei_code' => '404 ', 'ksei_name' => 'KONAWE UTARA '],
        ['id' => '7411', 'province_id' => '74', 'name' => 'KABUPATEN KOLAKA TIMUR', 'ksei_code' => '398 ', 'ksei_name' => 'KOLAKA '],
        ['id' => '7412', 'province_id' => '74', 'name' => 'KABUPATEN KONAWE KEPULAUAN', 'ksei_code' => '397 ', 'ksei_name' => 'KONAWE '],
        ['id' => '7413', 'province_id' => '74', 'name' => 'KABUPATEN MUNA BARAT', 'ksei_code' => '396 ', 'ksei_name' => 'MUNA '],
        ['id' => '7414', 'province_id' => '74', 'name' => 'KABUPATEN BUTON TENGAH', 'ksei_code' => '395 ', 'ksei_name' => 'BUTON '],
        ['id' => '7415', 'province_id' => '74', 'name' => 'KABUPATEN BUTON SELATAN', 'ksei_code' => '395 ', 'ksei_name' => 'BUTON '],
        ['id' => '7471', 'province_id' => '74', 'name' => 'KOTA KENDARI', 'ksei_code' => '405 ', 'ksei_name' => 'KENDARI '],
        ['id' => '7472', 'province_id' => '74', 'name' => 'KOTA BAUBAU', 'ksei_code' => '406 ', 'ksei_name' => 'BAU-BAU '],
        ['id' => '7501', 'province_id' => '75', 'name' => 'KABUPATEN BOALEMO', 'ksei_code' => '407 ', 'ksei_name' => 'BOALEMO '],
        ['id' => '7502', 'province_id' => '75', 'name' => 'KABUPATEN GORONTALO', 'ksei_code' => '412 ', 'ksei_name' => 'GORONTALO '],
        ['id' => '7503', 'province_id' => '75', 'name' => 'KABUPATEN POHUWATO', 'ksei_code' => '409 ', 'ksei_name' => 'POHUWATO '],
        ['id' => '7504', 'province_id' => '75', 'name' => 'KABUPATEN BONE BOLANGO', 'ksei_code' => '410 ', 'ksei_name' => 'BONE BOLANGO '],
        ['id' => '7505', 'province_id' => '75', 'name' => 'KABUPATEN GORONTALO UTARA', 'ksei_code' => '411 ', 'ksei_name' => 'GORONTALO UTARA '],
        ['id' => '7571', 'province_id' => '75', 'name' => 'KOTA GORONTALO', 'ksei_code' => '412 ', 'ksei_name' => 'GORONTALO '],
        ['id' => '7601', 'province_id' => '76', 'name' => 'KABUPATEN MAJENE', 'ksei_code' => '413 ', 'ksei_name' => 'MAJENE '],
        ['id' => '7602', 'province_id' => '76', 'name' => 'KABUPATEN POLEWALI MANDAR', 'ksei_code' => '414 ', 'ksei_name' => 'POLEWALI MANDAR '],
        ['id' => '7603', 'province_id' => '76', 'name' => 'KABUPATEN MAMASA', 'ksei_code' => '415 ', 'ksei_name' => 'MAMASA '],
        ['id' => '7604', 'province_id' => '76', 'name' => 'KABUPATEN MAMUJU', 'ksei_code' => '416 ', 'ksei_name' => 'MAMUJU '],
        ['id' => '7605', 'province_id' => '76', 'name' => 'KABUPATEN MAMUJU UTARA', 'ksei_code' => '417 ', 'ksei_name' => 'MAMUJU UTARA '],
        ['id' => '7606', 'province_id' => '76', 'name' => 'KABUPATEN MAMUJU TENGAH', 'ksei_code' => '416 ', 'ksei_name' => 'MAMUJU '],
        ['id' => '8101', 'province_id' => '81', 'name' => 'KABUPATEN MALUKU TENGGARA BARAT', 'ksei_code' => '418 ', 'ksei_name' => 'MALUKU TENGGARA BARAT '],
        ['id' => '8102', 'province_id' => '81', 'name' => 'KABUPATEN MALUKU TENGGARA', 'ksei_code' => '419 ', 'ksei_name' => 'MALUKU TENGGARA '],
        ['id' => '8103', 'province_id' => '81', 'name' => 'KABUPATEN MALUKU TENGAH', 'ksei_code' => '420 ', 'ksei_name' => 'MALUKU TENGAH '],
        ['id' => '8104', 'province_id' => '81', 'name' => 'KABUPATEN BURU', 'ksei_code' => '421 ', 'ksei_name' => 'BURU '],
        ['id' => '8105', 'province_id' => '81', 'name' => 'KABUPATEN KEPULAUAN ARU', 'ksei_code' => '422 ', 'ksei_name' => 'KEPULAUAN ARU '],
        ['id' => '8106', 'province_id' => '81', 'name' => 'KABUPATEN SERAM BAGIAN BARAT', 'ksei_code' => '423 ', 'ksei_name' => 'SERAM BAGIAN BARAT '],
        ['id' => '8107', 'province_id' => '81', 'name' => 'KABUPATEN SERAM BAGIAN TIMUR', 'ksei_code' => '424 ', 'ksei_name' => 'SERAM BAGIAN TIMUR '],
        ['id' => '8108', 'province_id' => '81', 'name' => 'KABUPATEN MALUKU BARAT DAYA', 'ksei_code' => '418 ', 'ksei_name' => 'MALUKU TENGGARA BARAT '],
        ['id' => '8109', 'province_id' => '81', 'name' => 'KABUPATEN BURU SELATAN', 'ksei_code' => '421 ', 'ksei_name' => 'BURU '],
        ['id' => '8171', 'province_id' => '81', 'name' => 'KOTA AMBON', 'ksei_code' => '426 ', 'ksei_name' => 'AMBON '],
        ['id' => '8172', 'province_id' => '81', 'name' => 'KOTA TUAL', 'ksei_code' => '425 ', 'ksei_name' => 'TUAL '],
        ['id' => '8201', 'province_id' => '82', 'name' => 'KABUPATEN HALMAHERA BARAT', 'ksei_code' => '427 ', 'ksei_name' => 'HALMAHERA BARAT '],
        ['id' => '8202', 'province_id' => '82', 'name' => 'KABUPATEN HALMAHERA TENGAH', 'ksei_code' => '428 ', 'ksei_name' => 'HALMAHERA TENGAH '],
        ['id' => '8203', 'province_id' => '82', 'name' => 'KABUPATEN KEPULAUAN SULA', 'ksei_code' => '429 ', 'ksei_name' => 'KEPULAUAN SULA '],
        ['id' => '8204', 'province_id' => '82', 'name' => 'KABUPATEN HALMAHERA SELATAN', 'ksei_code' => '430 ', 'ksei_name' => 'HALMAHERA SELATAN '],
        ['id' => '8205', 'province_id' => '82', 'name' => 'KABUPATEN HALMAHERA UTARA', 'ksei_code' => '431 ', 'ksei_name' => 'HALMAHERA UTARA '],
        ['id' => '8206', 'province_id' => '82', 'name' => 'KABUPATEN HALMAHERA TIMUR', 'ksei_code' => '432 ', 'ksei_name' => 'HALMAHERA TIMUR '],
        ['id' => '8207', 'province_id' => '82', 'name' => 'KABUPATEN PULAU MOROTAI', 'ksei_code' => '431 ', 'ksei_name' => 'HALMAHERA UTARA '],
        ['id' => '8208', 'province_id' => '82', 'name' => 'KABUPATEN PULAU TALIABU', 'ksei_code' => '429 ', 'ksei_name' => 'KEPULAUAN SULA '],
        ['id' => '8271', 'province_id' => '82', 'name' => 'KOTA TERNATE', 'ksei_code' => '433 ', 'ksei_name' => 'TERNATE '],
        ['id' => '8272', 'province_id' => '82', 'name' => 'KOTA TIDORE KEPULAUAN', 'ksei_code' => '434 ', 'ksei_name' => 'TIDORE KEPULAUAN '],
        ['id' => '9101', 'province_id' => '91', 'name' => 'KABUPATEN FAKFAK', 'ksei_code' => '435 ', 'ksei_name' => 'FAK-FAK '],
        ['id' => '9102', 'province_id' => '91', 'name' => 'KABUPATEN KAIMANA', 'ksei_code' => '436 ', 'ksei_name' => 'KAIMANA '],
        ['id' => '9103', 'province_id' => '91', 'name' => 'KABUPATEN TELUK WONDAMA', 'ksei_code' => '437 ', 'ksei_name' => 'TELUK WONDAMA '],
        ['id' => '9104', 'province_id' => '91', 'name' => 'KABUPATEN TELUK BINTUNI', 'ksei_code' => '438 ', 'ksei_name' => 'TELUK BINTUNI '],
        ['id' => '9105', 'province_id' => '91', 'name' => 'KABUPATEN MANOKWARI', 'ksei_code' => '439 ', 'ksei_name' => 'MANOKWARI '],
        ['id' => '9106', 'province_id' => '91', 'name' => 'KABUPATEN SORONG SELATAN', 'ksei_code' => '440 ', 'ksei_name' => 'SORONG SELATAN '],
        ['id' => '9107', 'province_id' => '91', 'name' => 'KABUPATEN SORONG', 'ksei_code' => '441 ', 'ksei_name' => 'SORONG '],
        ['id' => '9108', 'province_id' => '91', 'name' => 'KABUPATEN RAJA AMPAT', 'ksei_code' => '442 ', 'ksei_name' => 'RAJA AMPAT '],
        ['id' => '9109', 'province_id' => '91', 'name' => 'KABUPATEN TAMBRAUW', 'ksei_code' => '439 ', 'ksei_name' => 'MANOKWARI '],
        ['id' => '9110', 'province_id' => '91', 'name' => 'KABUPATEN MAYBRAT', 'ksei_code' => '441 ', 'ksei_name' => 'SORONG '],
        ['id' => '9111', 'province_id' => '91', 'name' => 'KABUPATEN MANOKWARI SELATAN', 'ksei_code' => '439 ', 'ksei_name' => 'MANOKWARI '],
        ['id' => '9112', 'province_id' => '91', 'name' => 'KABUPATEN PEGUNUNGAN ARFAK', 'ksei_code' => '439 ', 'ksei_name' => 'MANOKWARI '],
        ['id' => '9171', 'province_id' => '91', 'name' => 'KOTA SORONG', 'ksei_code' => '441 ', 'ksei_name' => 'SORONG '],
        ['id' => '9401', 'province_id' => '94', 'name' => 'KABUPATEN MERAUKE', 'ksei_code' => '444 ', 'ksei_name' => 'MERAUKE '],
        ['id' => '9402', 'province_id' => '94', 'name' => 'KABUPATEN JAYAWIJAYA', 'ksei_code' => '445 ', 'ksei_name' => 'JAYAWIJAYA '],
        ['id' => '9403', 'province_id' => '94', 'name' => 'KABUPATEN JAYAPURA', 'ksei_code' => '446 ', 'ksei_name' => 'JAYAPURA '],
        ['id' => '9404', 'province_id' => '94', 'name' => 'KABUPATEN NABIRE', 'ksei_code' => '447 ', 'ksei_name' => 'NABIRE '],
        ['id' => '9408', 'province_id' => '94', 'name' => 'KABUPATEN KEPULAUAN YAPEN', 'ksei_code' => '448 ', 'ksei_name' => 'YAPEN WAROPEN '],
        ['id' => '9409', 'province_id' => '94', 'name' => 'KABUPATEN BIAK NUMFOR', 'ksei_code' => '449 ', 'ksei_name' => 'BIAK NUMFOR '],
        ['id' => '9410', 'province_id' => '94', 'name' => 'KABUPATEN PANIAI', 'ksei_code' => '450 ', 'ksei_name' => 'PANIAI '],
        ['id' => '9411', 'province_id' => '94', 'name' => 'KABUPATEN PUNCAK JAYA', 'ksei_code' => '451 ', 'ksei_name' => 'PUNCAK JAYA '],
        ['id' => '9412', 'province_id' => '94', 'name' => 'KABUPATEN MIMIKA', 'ksei_code' => '452 ', 'ksei_name' => 'MIMIKA '],
        ['id' => '9413', 'province_id' => '94', 'name' => 'KABUPATEN BOVEN DIGOEL', 'ksei_code' => '453 ', 'ksei_name' => 'BOVEN DIGOEL '],
        ['id' => '9414', 'province_id' => '94', 'name' => 'KABUPATEN MAPPI', 'ksei_code' => '454 ', 'ksei_name' => 'MAPPI '],
        ['id' => '9415', 'province_id' => '94', 'name' => 'KABUPATEN ASMAT', 'ksei_code' => '455 ', 'ksei_name' => 'ASMAT '],
        ['id' => '9416', 'province_id' => '94', 'name' => 'KABUPATEN YAHUKIMO', 'ksei_code' => '456 ', 'ksei_name' => 'YAHUKIMO '],
        ['id' => '9417', 'province_id' => '94', 'name' => 'KABUPATEN PEGUNUNGAN BINTANG', 'ksei_code' => '457 ', 'ksei_name' => 'PEGUNUNGAN BINTANG '],
        ['id' => '9418', 'province_id' => '94', 'name' => 'KABUPATEN TOLIKARA', 'ksei_code' => '458 ', 'ksei_name' => 'TOLIKARA '],
        ['id' => '9419', 'province_id' => '94', 'name' => 'KABUPATEN SARMI', 'ksei_code' => '459 ', 'ksei_name' => 'SARMI '],
        ['id' => '9420', 'province_id' => '94', 'name' => 'KABUPATEN KEEROM', 'ksei_code' => '460 ', 'ksei_name' => 'KEEROM '],
        ['id' => '9426', 'province_id' => '94', 'name' => 'KABUPATEN WAROPEN', 'ksei_code' => '461 ', 'ksei_name' => 'WAROPEN '],
        ['id' => '9427', 'province_id' => '94', 'name' => 'KABUPATEN SUPIORI', 'ksei_code' => '462 ', 'ksei_name' => 'SUPIORI '],
        ['id' => '9428', 'province_id' => '94', 'name' => 'KABUPATEN MAMBERAMO RAYA', 'ksei_code' => '470 ', 'ksei_name' => 'MEMBERAMO RAYA '],
        ['id' => '9429', 'province_id' => '94', 'name' => 'KABUPATEN NDUGA', 'ksei_code' => '467 ', 'ksei_name' => 'NDUGA '],
        ['id' => '9430', 'province_id' => '94', 'name' => 'KABUPATEN LANNY JAYA', 'ksei_code' => '468 ', 'ksei_name' => 'LANNY JAYA '],
        ['id' => '9431', 'province_id' => '94', 'name' => 'KABUPATEN MAMBERAMO TENGAH', 'ksei_code' => '465 ', 'ksei_name' => 'NAMBERAMO '],
        ['id' => '9432', 'province_id' => '94', 'name' => 'KABUPATEN YALIMO', 'ksei_code' => '464 ', 'ksei_name' => 'YALIMO '],
        ['id' => '9433', 'province_id' => '94', 'name' => 'KABUPATEN PUNCAK', 'ksei_code' => '469 ', 'ksei_name' => 'PUNCAK '],
        ['id' => '9434', 'province_id' => '94', 'name' => 'KABUPATEN DOGIYAI', 'ksei_code' => '466 ', 'ksei_name' => 'DOGIYAI '],
        ['id' => '9435', 'province_id' => '94', 'name' => 'KABUPATEN INTAN JAYA', 'ksei_code' => '450 ', 'ksei_name' => 'PANIAI '],
        ['id' => '9436', 'province_id' => '94', 'name' => 'KABUPATEN DEIYAI', 'ksei_code' => '450 ', 'ksei_name' => 'PANIAI '],
        ['id' => '9471', 'province_id' => '94', 'name' => 'KOTA JAYAPURA', 'ksei_code' => '446 ', 'ksei_name' => 'JAYAPURA ']
      ];

      DB::table('cities')->insert($cities);
    }
}
