<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();

        $countries = [
          ['name' => 'ÅALAND ISLANDS', 'nationality' => 'ÅALAND ISLANDS', 'code' => 'AX'],
          ['name' => 'AFGHANISTAN', 'nationality' => 'AFGHAN', 'code' => 'AF'],
          ['name' => 'ALBANIA', 'nationality' => 'ALBANIAN', 'code' => 'AL'],
          ['name' => 'ALGERIA', 'nationality' => 'ALGERIAN', 'code' => 'DZ'],
          ['name' => 'AMERICAN SAMOA', 'nationality' => 'AMERICAN SAMOA', 'code' => 'AS'],
          ['name' => 'ANDORRA', 'nationality' => 'ANDORRAN', 'code' => 'AD'],
          ['name' => 'ANGOLA', 'nationality' => 'ANGOLAN', 'code' => 'AO'],
          ['name' => 'ANGUILLA', 'nationality' => 'ANGUILLA', 'code' => 'AI'],
          ['name' => 'ANTARCTICA', 'nationality' => 'ANTARCTICA', 'code' => 'AQ'],
          ['name' => 'ANTIGUA AND BARBUDA', 'nationality' => 'ANTIGUANS', 'code' => 'AG'],
          ['name' => 'ARGENTINA', 'nationality' => 'ARGENTINEAN', 'code' => 'AR'],
          ['name' => 'ARMENIA', 'nationality' => 'ARMENIAN', 'code' => 'AM'],
          ['name' => 'ARUBA', 'nationality' => 'ARUBA', 'code' => 'AW'],
          ['name' => 'AUSTRALIA', 'nationality' => 'AUSTRALIAN', 'code' => 'AU'],
          ['name' => 'AUSTRIA', 'nationality' => 'AUSTRIAN', 'code' => 'AT'],
          ['name' => 'AZERBAIJAN', 'nationality' => 'AZERBAIJANI', 'code' => 'AZ'],
          ['name' => 'BAHAMAS', 'nationality' => 'BAHAMIAN', 'code' => 'BS'],
          ['name' => 'BAHRAIN', 'nationality' => 'BAHRAINI', 'code' => 'BH'],
          ['name' => 'BANGLADESH', 'nationality' => 'BANGLADESHI', 'code' => 'BD'],
          ['name' => 'BARBADOS', 'nationality' => 'BARBADIAN', 'code' => 'BB'],
          ['name' => 'BELARUS', 'nationality' => 'BELARUSIAN', 'code' => 'BY'],
          ['name' => 'BELGIUM', 'nationality' => 'BELGIAN', 'code' => 'BE'],
          ['name' => 'BELIZE', 'nationality' => 'BELIZEAN', 'code' => 'BZ'],
          ['name' => 'BENIN', 'nationality' => 'BENINESE', 'code' => 'BJ'],
          ['name' => 'BERMUDA', 'nationality' => 'BERMUDIAN', 'code' => 'BM'],
          ['name' => 'BHUTAN', 'nationality' => 'BHUTANESE', 'code' => 'BT'],
          ['name' => 'BOLIVIA, PLURINATIONAL STATE OF', 'nationality' => 'BOLIVIAN', 'code' => 'BO'],
          ['name' => 'BONAIRE, SINT EUSTATIUS AND SABA', 'nationality' => 'BONAIRE, SINT EUSTATIUS AND SABA', 'code' => 'BQ'],
          ['name' => 'BOSNIA AND HERZEGOVINA', 'nationality' => 'BOSNIAN', 'code' => 'BA'],
          ['name' => 'BOTSWANA', 'nationality' => 'BATSWANA', 'code' => 'BW'],
          ['name' => 'BOUVET ISLAND', 'nationality' => 'BOUVET ISLAND', 'code' => 'BV'],
          ['name' => 'BRAZIL', 'nationality' => 'BRAZILIAN', 'code' => 'BR'],
          ['name' => 'BRITISH INDIAN OCEAN TERRITORY', 'nationality' => 'BRITISH INDIAN OCEAN TERRITORY', 'code' => 'IO'],
          ['name' => 'BRUNEI DARUSSALAM', 'nationality' => 'BRUNEIAN', 'code' => 'BN'],
          ['name' => 'BULGARIA', 'nationality' => 'BULGARIAN', 'code' => 'BG'],
          ['name' => 'BURKINA FASO', 'nationality' => 'BURKINABE', 'code' => 'BF'],
          ['name' => 'BURUNDI', 'nationality' => 'BURUNDIAN', 'code' => 'BI'],
          ['name' => 'CAMBODIA', 'nationality' => 'CAMBODIAN', 'code' => 'KH'],
          ['name' => 'CAMEROON', 'nationality' => 'CAMEROONIAN', 'code' => 'CM'],
          ['name' => 'CANADA', 'nationality' => 'CANADIAN', 'code' => 'CA'],
          ['name' => 'CAPE VERDE', 'nationality' => 'CAPE VERDEAN', 'code' => 'CV'],
          ['name' => 'CAYMAN ISLANDS', 'nationality' => 'CAYMANIAN', 'code' => 'KY'],
          ['name' => 'CENTRAL AFRICAN REPUBLIC', 'nationality' => 'CENTRAL AFRICAN', 'code' => 'CF'],
          ['name' => 'CHAD', 'nationality' => 'CHADIAN', 'code' => 'TD'],
          ['name' => 'CHILE', 'nationality' => 'CHILEAN', 'code' => 'CL'],
          ['name' => 'CHINA', 'nationality' => 'CHINESE', 'code' => 'CN'],
          ['name' => 'CHRISTMAS ISLAND', 'nationality' => 'CHRISTMAS ISLAND', 'code' => 'CX'],
          ['name' => 'COCOS (KEELING) ISLANDS', 'nationality' => 'COCOS ISLANDS', 'code' => 'CC'],
          ['name' => 'COLOMBIA', 'nationality' => 'COLOMBIAN', 'code' => 'CO'],
          ['name' => 'COMOROS', 'nationality' => 'COMORAN', 'code' => 'KM'],
          ['name' => 'CONGO', 'nationality' => 'REPUBLIC OF THE CONGO', 'code' => 'CG'],
          ['name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'nationality' => 'CONGOLESE', 'code' => 'CD'],
          ['name' => 'COOK ISLANDS', 'nationality' => 'COOK ISLANDS', 'code' => 'CK'],
          ['name' => 'COSTA RICA', 'nationality' => 'COSTA RICAN', 'code' => 'CR'],
          ['name' => 'CÔTE D\'IVOIRE', 'nationality' => 'IVORIAN', 'code' => 'CI'],
          ['name' => 'CROATIA', 'nationality' => 'CROATIAN', 'code' => 'HR'],
          ['name' => 'CUBA', 'nationality' => 'CUBAN', 'code' => 'CU'],
          ['name' => 'CURAÇAO', 'nationality' => 'CURAÇAO', 'code' => 'CW'],
          ['name' => 'CYPRUS', 'nationality' => 'CYPRIOT', 'code' => 'CY'],
          ['name' => 'CZECH REPUBLIC', 'nationality' => 'CZECH', 'code' => 'CZ'],
          ['name' => 'DENMARK', 'nationality' => 'DANISH', 'code' => 'DK'],
          ['name' => 'DJIBOUTI', 'nationality' => 'DJIBOUTI', 'code' => 'DJ'],
          ['name' => 'DOMINICA', 'nationality' => 'DOMINICAN', 'code' => 'DM'],
          ['name' => 'DOMINICAN REPUBLIC', 'nationality' => 'DOMINICAN REPUBLIC', 'code' => 'DO'],
          ['name' => 'ECUADOR', 'nationality' => 'ECUADOREAN', 'code' => 'EC'],
          ['name' => 'EGYPT', 'nationality' => 'EGYPTIAN', 'code' => 'EG'],
          ['name' => 'EL SALVADOR', 'nationality' => 'SALVADORAN', 'code' => 'SV'],
          ['name' => 'EQUATORIAL GUINEA', 'nationality' => 'EQUATORIAL GUINEAN', 'code' => 'GQ'],
          ['name' => 'ERITREA', 'nationality' => 'ERITREAN', 'code' => 'ER'],
          ['name' => 'ESTONIA', 'nationality' => 'ESTONIAN', 'code' => 'EE'],
          ['name' => 'ETHIOPIA', 'nationality' => 'ETHIOPIAN', 'code' => 'ET'],
          ['name' => 'FALKLAND ISLANDS (MALVINAS)', 'nationality' => 'FALKLAND ISLANDS (MALVINAS)', 'code' => 'FK'],
          ['name' => 'FAROE ISLANDS', 'nationality' => 'FAROE ISLANDS', 'code' => 'FO'],
          ['name' => 'FIJI', 'nationality' => 'FIJIAN', 'code' => 'FJ'],
          ['name' => 'FINLAND', 'nationality' => 'FINNISH', 'code' => 'FI'],
          ['name' => 'FRANCE', 'nationality' => 'FRENCH', 'code' => 'FR'],
          ['name' => 'FRENCH GUIANA', 'nationality' => 'FRENCH GUIANA', 'code' => 'GF'],
          ['name' => 'FRENCH POLYNESIA', 'nationality' => 'FRENCH POLYNESIA', 'code' => 'PF'],
          ['name' => 'FRENCH SOUTHERN TERRITORIES', 'nationality' => 'FRENCH SOUTHERN AND ANTARCTIC LANDS', 'code' => 'TF'],
          ['name' => 'GABON', 'nationality' => 'GABONESE', 'code' => 'GA'],
          ['name' => 'GAMBIA', 'nationality' => 'GAMBIAN', 'code' => 'GM'],
          ['name' => 'GEORGIA', 'nationality' => 'GEORGIAN', 'code' => 'GE'],
          ['name' => 'GERMANY', 'nationality' => 'GERMAN', 'code' => 'DE'],
          ['name' => 'GHANA', 'nationality' => 'GHANAIAN', 'code' => 'GH'],
          ['name' => 'GIBRALTAR', 'nationality' => 'GIBRALTARIAN', 'code' => 'GI'],
          ['name' => 'GREECE', 'nationality' => 'GREEK', 'code' => 'GR'],
          ['name' => 'GREENLAND', 'nationality' => 'GREENLAND', 'code' => 'GL'],
          ['name' => 'GRENADA', 'nationality' => 'GRENADIAN', 'code' => 'GD'],
          ['name' => 'GUADELOUPE', 'nationality' => 'GUADELOUPE', 'code' => 'GP'],
          ['name' => 'GUAM', 'nationality' => 'GUAM', 'code' => 'GU'],
          ['name' => 'GUATEMALA', 'nationality' => 'GUATEMALAN', 'code' => 'GT'],
          ['name' => 'GUERNSEY', 'nationality' => 'GUERNSEY', 'code' => 'GG'],
          ['name' => 'GUINEA', 'nationality' => 'GUINEAN', 'code' => 'GN'],
          ['name' => 'GUINEA-BISSAU', 'nationality' => 'GUINEA-BISSAUAN', 'code' => 'GW'],
          ['name' => 'GUYANA', 'nationality' => 'GUYANESE', 'code' => 'GY'],
          ['name' => 'HAITI', 'nationality' => 'HAITIAN', 'code' => 'HT'],
          ['name' => 'HEARD ISLAND AND MCDONALD ISLANDS', 'nationality' => 'HEARD ISLAND AND MCDONALD ISLANDS', 'code' => 'HM'],
          ['name' => 'HOLY SEE (VATICAN CITY STATE)', 'nationality' => 'HOLY SEE (VATICAN CITY STATE)', 'code' => 'VA'],
          ['name' => 'HONDURAS', 'nationality' => 'HONDURAN', 'code' => 'HN'],
          ['name' => 'HONG KONG', 'nationality' => 'HONG KONG', 'code' => 'HK'],
          ['name' => 'HUNGARY', 'nationality' => 'HUNGARIAN', 'code' => 'HU'],
          ['name' => 'ICELAND', 'nationality' => 'ICELANDER', 'code' => 'IS'],
          ['name' => 'INDIA', 'nationality' => 'INDIAN', 'code' => 'IN'],
          ['name' => 'INDONESIA', 'nationality' => 'INDONESIAN', 'code' => 'ID'],
          ['name' => 'IRAN, ISLAMIC REPUBLIC OF', 'nationality' => 'IRANIAN', 'code' => 'IR'],
          ['name' => 'IRAQ', 'nationality' => 'IRAQI', 'code' => 'IQ'],
          ['name' => 'IRELAND', 'nationality' => 'IRISH', 'code' => 'IE'],
          ['name' => 'ISLE OF MAN', 'nationality' => 'ISLE OF MAN', 'code' => 'IM'],
          ['name' => 'ISRAEL', 'nationality' => 'ISRAELI', 'code' => 'IL'],
          ['name' => 'ITALY', 'nationality' => 'ITALIAN', 'code' => 'IT'],
          ['name' => 'JAMAICA', 'nationality' => 'JAMAICAN', 'code' => 'JM'],
          ['name' => 'JAPAN', 'nationality' => 'JAPANESE', 'code' => 'JP'],
          ['name' => 'JERSEY', 'nationality' => 'JERSEY', 'code' => 'JE'],
          ['name' => 'JORDAN', 'nationality' => 'JORDANIAN', 'code' => 'JO'],
          ['name' => 'KAZAKHSTAN', 'nationality' => 'KAZAKHSTANI', 'code' => 'KZ'],
          ['name' => 'KENYA', 'nationality' => 'KENYAN', 'code' => 'KE'],
          ['name' => 'KIRIBATI', 'nationality' => 'I-KIRIBATI', 'code' => 'KI'],
          ['name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'nationality' => 'NORTH KOREAN', 'code' => 'KP'],
          ['name' => 'KOREA, REPUBLIC OF', 'nationality' => 'SOUTH KOREAN', 'code' => 'KR'],
          ['name' => 'KUWAIT', 'nationality' => 'KUWAITI', 'code' => 'KW'],
          ['name' => 'KYRGYZSTAN', 'nationality' => 'KYRGYZ', 'code' => 'KG'],
          ['name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'nationality' => 'LAOTIAN', 'code' => 'LA'],
          ['name' => 'LATVIA', 'nationality' => 'LATVIAN', 'code' => 'LV'],
          ['name' => 'LEBANON', 'nationality' => 'LEBANESE', 'code' => 'LB'],
          ['name' => 'LESOTHO', 'nationality' => 'LESOTHO', 'code' => 'LS'],
          ['name' => 'LIBERIA', 'nationality' => 'LIBERIAN', 'code' => 'LR'],
          ['name' => 'LIBYA', 'nationality' => 'LIBYAN', 'code' => 'LY'],
          ['name' => 'LIECHTENSTEIN', 'nationality' => 'LIECHTENSTEINER', 'code' => 'LI'],
          ['name' => 'LITHUANIA', 'nationality' => 'LITHUANIAN', 'code' => 'LT'],
          ['name' => 'LUXEMBOURG', 'nationality' => 'LUXEMBOURGER', 'code' => 'LU'],
          ['name' => 'MACAO', 'nationality' => 'MACAU', 'code' => 'MO'],
          ['name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'nationality' => 'MACEDONIAN', 'code' => 'MK'],
          ['name' => 'MADAGASCAR', 'nationality' => 'MALAGASY', 'code' => 'MG'],
          ['name' => 'MALAWI', 'nationality' => 'MALAWIAN', 'code' => 'MW'],
          ['name' => 'MALAYSIA', 'nationality' => 'MALAYSIAN', 'code' => 'MY'],
          ['name' => 'MALDIVES', 'nationality' => 'MALDIVAN', 'code' => 'MV'],
          ['name' => 'MALI', 'nationality' => 'MALIAN', 'code' => 'ML'],
          ['name' => 'MALTA', 'nationality' => 'MALTESE', 'code' => 'MT'],
          ['name' => 'MARSHALL ISLANDS', 'nationality' => 'MARSHALLESE', 'code' => 'MH'],
          ['name' => 'MARTINIQUE', 'nationality' => 'MARTINIQUE', 'code' => 'MQ'],
          ['name' => 'MAURITANIA', 'nationality' => 'MAURITANIAN', 'code' => 'MR'],
          ['name' => 'MAURITIUS', 'nationality' => 'MAURITIAN', 'code' => 'MU'],
          ['name' => 'MAYOTTE', 'nationality' => 'MAYOTTE', 'code' => 'YT'],
          ['name' => 'MEXICO', 'nationality' => 'MEXICAN', 'code' => 'MX'],
          ['name' => 'MICRONESIA, FEDERATED STATES OF', 'nationality' => 'MICRONESIAN', 'code' => 'FM'],
          ['name' => 'MOLDOVA, REPUBLIC OF', 'nationality' => 'MOLDOVAN', 'code' => 'MD'],
          ['name' => 'MONACO', 'nationality' => 'MONACAN', 'code' => 'MC'],
          ['name' => 'MONGOLIA', 'nationality' => 'MONGOLIAN', 'code' => 'MN'],
          ['name' => 'MONTENEGRO', 'nationality' => 'MONTENEGRO', 'code' => 'ME'],
          ['name' => 'MONTSERRAT', 'nationality' => 'MONTSERRAT', 'code' => 'MS'],
          ['name' => 'MOROCCO', 'nationality' => 'MOROCCAN', 'code' => 'MA'],
          ['name' => 'MOZAMBIQUE', 'nationality' => 'MOZAMBICAN', 'code' => 'MZ'],
          ['name' => 'MYANMAR', 'nationality' => 'BURMESE', 'code' => 'MM'],
          ['name' => 'NAMIBIA', 'nationality' => 'NAMIBIAN', 'code' => 'NA'],
          ['name' => 'NAURU', 'nationality' => 'NAURUAN', 'code' => 'NR'],
          ['name' => 'NEPAL', 'nationality' => 'NEPALESE', 'code' => 'NP'],
          ['name' => 'NETHERLANDS', 'nationality' => 'NETHERLANDER', 'code' => 'NL'],
          ['name' => 'NEW CALEDONIA', 'nationality' => 'NEW CALEDONIA', 'code' => 'NC'],
          ['name' => 'NEW ZEALAND', 'nationality' => 'NEW ZEALANDER', 'code' => 'NZ'],
          ['name' => 'NICARAGUA', 'nationality' => 'NICARAGUAN', 'code' => 'NI'],
          ['name' => 'NIGER', 'nationality' => 'NIGERIAN', 'code' => 'NE'],
          ['name' => 'NIGERIA', 'nationality' => 'NIGERIEN', 'code' => 'NG'],
          ['name' => 'NIUE', 'nationality' => 'NI-VANUATU', 'code' => 'NU'],
          ['name' => 'NORFOLK ISLAND', 'nationality' => 'NORFOLK ISLAND', 'code' => 'NF'],
          ['name' => 'NORTHERN MARIANA ISLANDS', 'nationality' => 'NORTHERN MARIANA ISLANDS', 'code' => 'MP'],
          ['name' => 'NORWAY', 'nationality' => 'NORWEGIAN', 'code' => 'NO'],
          ['name' => 'OMAN', 'nationality' => 'OMANI', 'code' => 'OM'],
          ['name' => 'PAKISTAN', 'nationality' => 'PAKISTANI', 'code' => 'PK'],
          ['name' => 'PALAU', 'nationality' => 'PALAUAN', 'code' => 'PW'],
          ['name' => 'PALESTINIAN TERRITORY, OCCUPIED', 'nationality' => 'PALESTINIAN TERRITORY, OCCUPIED', 'code' => 'PS'],
          ['name' => 'PANAMA', 'nationality' => 'PANAMANIAN', 'code' => 'PA'],
          ['name' => 'PAPUA NEW GUINEA', 'nationality' => 'PAPUA NEW GUINEAN', 'code' => 'PG'],
          ['name' => 'PARAGUAY', 'nationality' => 'PARAGUAYAN', 'code' => 'PY'],
          ['name' => 'PERU', 'nationality' => 'PERUVIAN', 'code' => 'PE'],
          ['name' => 'PHILIPPINES', 'nationality' => 'FILIPINO', 'code' => 'PH'],
          ['name' => 'PITCAIRN', 'nationality' => 'PITCAIRN ISLANDS', 'code' => 'PN'],
          ['name' => 'POLAND ', 'nationality' => 'POLISH ', 'code' => 'PL'],
          ['name' => 'PORTUGAL ', 'nationality' => 'PORTUGUESE ', 'code' => 'PT'],
          ['name' => 'PUERTO RICO ', 'nationality' => 'PUERTO RICO ', 'code' => 'PR'],
          ['name' => 'QATAR ', 'nationality' => 'QATARI ', 'code' => 'QA'],
          ['name' => 'RÉUNION ', 'nationality' => 'REUNION ', 'code' => 'RE'],
          ['name' => 'ROMANIA ', 'nationality' => 'ROMANIAN ', 'code' => 'RO'],
          ['name' => 'RUSSIAN FEDERATION ', 'nationality' => 'RUSSIAN ', 'code' => 'RU'],
          ['name' => 'RWANDA ', 'nationality' => 'RWANDAN ', 'code' => 'RW'],
          ['name' => 'SAINT BARTHÉLEMY ', 'nationality' => 'SAINT-BARTH?LEMY ', 'code' => 'BL'],
          ['name' => 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA ', 'nationality' => 'SAINT HELENIANS ', 'code' => 'SH'],
          ['name' => 'SAINT KITTS AND NEVIS ', 'nationality' => 'SAINT KITTS AND NEVIS ', 'code' => 'KN'],
          ['name' => 'SAINT LUCIA ', 'nationality' => 'SAINT LUCIAN ', 'code' => 'LC'],
          ['name' => 'SAINT MARTIN (FRENCH PART) ', 'nationality' => 'SAINT-MARTIN (FRENCH PART) ', 'code' => 'MF'],
          ['name' => 'SAINT PIERRE AND MIQUELON ', 'nationality' => 'SAINT PIERRE AND MIQUELON ', 'code' => 'PM'],
          ['name' => 'SAINT VINCENT AND THE GRENADINES ', 'nationality' => 'SAINT VINCENT AND THE GRENADINES ', 'code' => 'VC'],
          ['name' => 'SAMOA ', 'nationality' => 'SAMOAN ', 'code' => 'WS'],
          ['name' => 'SAN MARINO ', 'nationality' => 'SAN MARINESE ', 'code' => 'SM'],
          ['name' => 'SAO TOME AND PRINCIPE ', 'nationality' => 'SAO TOMEAN ', 'code' => 'ST'],
          ['name' => 'SAUDI ARABIA ', 'nationality' => 'SAUDI ', 'code' => 'SA'],
          ['name' => 'SENEGAL ', 'nationality' => 'SENEGALESE ', 'code' => 'SN'],
          ['name' => 'SERBIA ', 'nationality' => 'SERBIAN ', 'code' => 'RS'],
          ['name' => 'SEYCHELLES ', 'nationality' => 'SEYCHELLOIS ', 'code' => 'SC'],
          ['name' => 'SIERRA LEONE ', 'nationality' => 'SIERRA LEONEAN ', 'code' => 'SL'],
          ['name' => 'SINGAPORE ', 'nationality' => 'SINGAPOREAN ', 'code' => 'SG'],
          ['name' => 'SINT MAARTEN (DUTCH PART) ', 'nationality' => 'SINT MAARTEN (DUTCH PART) ', 'code' => 'SX'],
          ['name' => 'SLOVAKIA ', 'nationality' => 'SLOVAKIAN ', 'code' => 'SK'],
          ['name' => 'SLOVENIA ', 'nationality' => 'SLOVENIAN ', 'code' => 'SI'],
          ['name' => 'SOLOMON ISLANDS ', 'nationality' => 'SOLOMON ISLANDER ', 'code' => 'SB'],
          ['name' => 'SOMALIA ', 'nationality' => 'SOMALI ', 'code' => 'SO'],
          ['name' => 'SOUTH AFRICA ', 'nationality' => 'SOUTH AFRICAN ', 'code' => 'ZA'],
          ['name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS ', 'nationality' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS ', 'code' => 'GS'],
          ['name' => 'SOUTH SUDAN ', 'nationality' => 'SOUTH SUDANESE ', 'code' => 'SS'],
          ['name' => 'SPAIN ', 'nationality' => 'SPANISH ', 'code' => 'ES'],
          ['name' => 'SRI LANKA ', 'nationality' => 'SRI LANKAN ', 'code' => 'LK'],
          ['name' => 'SUDAN ', 'nationality' => 'SUDANESE ', 'code' => 'SD'],
          ['name' => 'SURINAME ', 'nationality' => 'SURINAMER ', 'code' => 'SR'],
          ['name' => 'SVALBARD AND JAN MAYEN ', 'nationality' => 'SVALBARD ', 'code' => 'SJ'],
          ['name' => 'SWAZILAND ', 'nationality' => 'SWAZI ', 'code' => 'SZ'],
          ['name' => 'SWEDEN ', 'nationality' => 'SWEDISH ', 'code' => 'SE'],
          ['name' => 'SWITZERLAND ', 'nationality' => 'SWISS ', 'code' => 'CH'],
          ['name' => 'SYRIAN ARAB REPUBLIC ', 'nationality' => 'SYRIAN ', 'code' => 'SY'],
          ['name' => 'TAIWAN, PROVINCE OF CHINA ', 'nationality' => 'TAIWANESE ', 'code' => 'TW'],
          ['name' => 'TAJIKISTAN ', 'nationality' => 'TAJIK ', 'code' => 'TJ'],
          ['name' => 'TANZANIA, UNITED REPUBLIC OF ', 'nationality' => 'TANZANIAN ', 'code' => 'TZ'],
          ['name' => 'THAILAND ', 'nationality' => 'THAI ', 'code' => 'TH'],
          ['name' => 'TIMOR-LESTE ', 'nationality' => 'EAST TIMORESE ', 'code' => 'TL'],
          ['name' => 'TOGO ', 'nationality' => 'TOGOLESE ', 'code' => 'TG'],
          ['name' => 'TOKELAU ', 'nationality' => 'TOKELAU ', 'code' => 'TK'],
          ['name' => 'TONGA ', 'nationality' => 'TONGAN ', 'code' => 'TO'],
          ['name' => 'TRINIDAD AND TOBAGO ', 'nationality' => 'TRINIDADIAN OR TOBAGONIAN ', 'code' => 'TT'],
          ['name' => 'TUNISIA ', 'nationality' => 'TUNISIAN ', 'code' => 'TN'],
          ['name' => 'TURKEY ', 'nationality' => 'TURKISH ', 'code' => 'TR'],
          ['name' => 'TURKMENISTAN ', 'nationality' => 'TURKMENISTAN ', 'code' => 'TM'],
          ['name' => 'TURKS AND CAICOS ISLANDS ', 'nationality' => 'TURKS AND CAICOS ISLANDS ', 'code' => 'TC'],
          ['name' => 'TUVALU ', 'nationality' => 'TUVALUAN ', 'code' => 'TV'],
          ['name' => 'UGANDA ', 'nationality' => 'UGANDAN ', 'code' => 'UG'],
          ['name' => 'UKRAINE ', 'nationality' => 'UKRAINIAN ', 'code' => 'UA'],
          ['name' => 'UNITED ARAB EMIRATES ', 'nationality' => 'UAE ', 'code' => 'AE'],
          ['name' => 'UNITED KINGDOM ', 'nationality' => 'BRITISH ', 'code' => 'GB'],
          ['name' => 'UNITED STATES ', 'nationality' => 'AMERICAN ', 'code' => 'US'],
          ['name' => 'UNITED STATES MINOR OUTLYING ISLANDS ', 'nationality' => 'UNITED STATES MINOR OUTLYING ISLANDS ', 'code' => 'UM'],
          ['name' => 'URUGUAY ', 'nationality' => 'URUGUAYAN ', 'code' => 'UY'],
          ['name' => 'UZBEKISTAN ', 'nationality' => 'UZBEKISTANI ', 'code' => 'UZ'],
          ['name' => 'VANUATU ', 'nationality' => 'VANUATU ', 'code' => 'VU'],
          ['name' => 'VENEZUELA, BOLIVARIAN REPUBLIC OF ', 'nationality' => 'VENEZUELAN ', 'code' => 'VE'],
          ['name' => 'VIET NAM ', 'nationality' => 'VIETNAMESE ', 'code' => 'VN'],
          ['name' => 'VIRGIN ISLANDS, BRITISH ', 'nationality' => 'BRITISH VIRGIN ISLANDER ', 'code' => 'VG'],
          ['name' => 'VIRGIN ISLANDS, U.S. ', 'nationality' => 'VIRGIN ISLANDS ', 'code' => 'VI'],
          ['name' => 'WALLIS AND FUTUNA ', 'nationality' => 'WALLIS AND FUTUNA ', 'code' => 'WF'],
          ['name' => 'WESTERN SAHARA ', 'nationality' => 'WESTERN SAHARA ', 'code' => 'EH'],
          ['name' => 'YEMEN ', 'nationality' => 'YEMENITE ', 'code' => 'YE'],
          ['name' => 'ZAMBIA ', 'nationality' => 'ZAMBIAN ', 'code' => 'ZM'],
          ['name' => 'ZIMBABWE ', 'nationality' => 'ZIMBABWEAN ', 'code' => 'ZW']
        ];

        DB::table('countries')->insert($countries);
    }
}
